In [1]:
# 日線量價吞噬前根紅Ｋ 進場
# RSI > 68 & KD > 80 或 紅Ｋ貫穿布林Ｍ往下 (第二條件實測發現吃掉大量停利空間)
# ! conda install -c conda-forge ta --yes

In [2]:
import websocket
import requests
import json
import pandas as pd
import ta
import matplotlib.pyplot as plt
import math
import pytz
import datetime as dt
import numpy as np
import time

In [3]:
timezone = 8
endpoint = 'wss://stream.binance.com:9443/ws'
symbol = 'ethusdt'
symbol_C = symbol.upper()
rate = 30
interval = '1d'
limit = 1000

# start epoch till now
start_time = 1641020207000
end_time = round(time.time() * 1000)

# step between timestamps in milliseconds, 60000 = 1min
step = 60000 * 60 * 24 # 15min

In [4]:
def get_historical(symbol, interval, start_time, end_time, step):
    
    df = pd.DataFrame()
    
    url = "https://api.binance.com/api/v3/klines"
    
    for timestamp in range(start_time, end_time, step):
        params = {"symbol": symbol_C,
                  "interval": interval,
                  "startTime": timestamp,
                  "endTime": timestamp + step}
        response = requests.get(url, params=params).json()
        out = pd.DataFrame(response, columns = ["Open time", "Open", "High", "Low", "Close",
                                               "Volume", "Close_Time", "Quote asset volume",
                                               "Number of trades", "Taker buy base asset volume",
                                               "Taker buy quote asset volume", "Ignore"])
        df = pd.concat([df, out], axis = 0)
    
    return df

In [5]:
df = get_historical(symbol, interval, start_time, end_time, step)

# filter columns, adjust data type
df = df[['Close_Time', 'Open', 'Close', "High", "Low", 'Volume']]
convert_dict = {'Close_Time': float, 'Open': float, 'Close': float, "High": float, "Low": float, 'Volume': float}
df = df.astype(convert_dict)

# adjust time to readable format and adjust timezone
df['Close_Time'] = pd.to_datetime(df['Close_Time'], unit = 'ms')
df['Close_Time'] = df['Close_Time'] + pd.Timedelta(hours=timezone)

# set proper index
df = df.reset_index(drop=True)

# for further iterations, to prevent time consumption in fetching raw data 
rawdf = df.copy()

print(df)

                       Close_Time     Open    Close     High      Low  \
0   2022-01-03 07:59:59.999000064  3765.54  3828.27  3857.44  3717.30
1   2022-01-04 07:59:59.999000064  3828.11  3765.89  3853.09  3680.00
2   2022-01-05 07:59:59.999000064  3765.89  3785.11  3900.73  3713.11
3   2022-01-06 07:59:59.999000064  3785.10  3540.63  3848.00  3415.00
4   2022-01-07 07:59:59.999000064  3539.82  3406.81  3550.43  3300.00
..                            ...      ...      ...      ...      ...
406 2023-02-13 07:59:59.999000064  1538.50  1514.83  1548.02  1493.08
407 2023-02-14 07:59:59.999000064  1514.82  1505.24  1526.10  1461.93
408 2023-02-15 07:59:59.999000064  1505.25  1555.71  1569.00  1482.66
409 2023-02-16 07:59:59.999000064  1555.70  1674.92  1680.00  1542.55
410 2023-02-17 07:59:59.999000064  1674.92  1689.35  1712.24  1672.53

          Volume
0    154791.4263
1    236245.8586
2    288258.5549
3    397942.0363
4    496745.7413
..           ...
406  286758.3740
407  643152.3904
408  668964.3768
409  581207.8586
410  294148.1880

[411 rows x 6 columns]

In [6]:
df = rawdf.copy()
print(rawdf)

                       Close_Time     Open    Close     High      Low  \
0   2022-01-03 07:59:59.999000064  3765.54  3828.27  3857.44  3717.30
1   2022-01-04 07:59:59.999000064  3828.11  3765.89  3853.09  3680.00
2   2022-01-05 07:59:59.999000064  3765.89  3785.11  3900.73  3713.11
3   2022-01-06 07:59:59.999000064  3785.10  3540.63  3848.00  3415.00
4   2022-01-07 07:59:59.999000064  3539.82  3406.81  3550.43  3300.00
..                            ...      ...      ...      ...      ...
406 2023-02-13 07:59:59.999000064  1538.50  1514.83  1548.02  1493.08
407 2023-02-14 07:59:59.999000064  1514.82  1505.24  1526.10  1461.93
408 2023-02-15 07:59:59.999000064  1505.25  1555.71  1569.00  1482.66
409 2023-02-16 07:59:59.999000064  1555.70  1674.92  1680.00  1542.55
410 2023-02-17 07:59:59.999000064  1674.92  1689.35  1712.24  1672.53

          Volume
0    154791.4263
1    236245.8586
2    288258.5549
3    397942.0363
4    496745.7413
..           ...
406  286758.3740
407  643152.3904
408  668964.3768
409  581207.8586
410  294148.1880

[411 rows x 6 columns]

In [7]:
def indicators(df):
# bband
    bb_int = 30
    bb_dev = 2
    bb = ta.volatility.BollingerBands(df['Close'], window=bb_int, window_dev=bb_dev)
    df['bb_u'] = bb.bollinger_hband()
    df['bb_m'] = bb.bollinger_mavg()
    df['bb_l'] = bb.bollinger_lband()
# rsi
    rsi_int = 14
    df['rsi'] = ta.momentum.RSIIndicator(df['Close'], window = rsi_int).rsi()
# kd
    kd_int = 14
    d_int = 3
    
    # Calculate Stochastic Oscillator
    kddf = pd.DataFrame()
    kddf[str(kd_int) + '-Low'] = df['Low'].rolling(kd_int).min()
    kddf[str(kd_int) + '-High'] = df['High'].rolling(kd_int).max()
    df['slowk'] = (df['Close'] - kddf[str(kd_int) + '-Low'])*100/(kddf[str(kd_int) + '-High'] - kddf[str(kd_int) + '-Low'])
    df['slowd'] = df['slowk'].rolling(d_int).mean()
    return df

In [8]:
indicators(df)

,Close_Time,Open,Close,High,Low,Volume,bb_u,bb_m,bb_l,rsi,slowk,slowd
0,2022-01-03 07:59:59.999000064,3765.54,3828.27,3857.44,3717.30,154791.4263,NaN,NaN,NaN,NaN,NaN,NaN
1,2022-01-04 07:59:59.999000064,3828.11,3765.89,3853.09,3680.00,236245.8586,NaN,NaN,NaN,NaN,NaN,NaN
2,2022-01-05 07:59:59.999000064,3765.89,3785.11,3900.73,3713.11,288258.5549,NaN,NaN,NaN,NaN,NaN,NaN
3,2022-01-06 07:59:59.999000064,3785.10,3540.63,3848.00,3415.00,397942.0363,NaN,NaN,NaN,NaN,NaN,NaN
4,2022-01-07 07:59:59.999000064,3539.82,3406.81,3550.43,3300.00,496745.7413,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
406,2023-02-13 07:59:59.999000064,1538.50,1514.83,1548.02,1493.08,286758.3740,1692.521488,1595.751667,1498.981846,44.919076,11.051273,14.301822
407,2023-02-14 07:59:59.999000064,1514.82,1505.24,1526.10,1461.93,643152.3904,1695.097180,1594.263000,1493.428820,43.977097,17.135509,16.592496
408,2023-02-15 07:59:59.999000064,1505.25,1555.71,1569.00,1482.66,668964.3768,1695.033796,1594.369333,1493.704870,49.928268,37.103858,21.763547
409,2023-02-16 07:59:59.999000064,1555.70,1674.92,1680.00,1542.55,581207.8586,1702.111571,1597.635333,1493.159096,60.579947,84.269041,46.169469
410,2023-02-17 07:59:59.999000064,1674.92,1689.35,1712.24,1672.53,294148.1880,1710.534682,1601.761333,1492.987985,61.643604,90.855339,70.742746

In [9]:
def conditions(df):

    # c1 日線收在下布林
    # c2 本Ｋ為綠Ｋ 前一天為紅Ｋ
    # c3 量大於前日
    # c4 收盤大於前日開盤

    for index, row in df.iterrows():
        # c1
        df['c1'] = df['Close'] < df['bb_m']
        # c2
        df['c2'] = (df['Close'] - df['Open'] > 0) & (df['Close'].shift(1) - df['Open'].shift(1) < 0) 
        # c3
        df['c3'] = df['Volume'] > df['Volume'].shift(1)
        # c4
        df['c4'] = df['Close'] > df['Open']

    # 條件達成
    df['signal'] = False
    df.loc[df.c1 & df.c2 & df.c3 & df.c4 , 'signal'] = True


    # 下一根進場
    df['openbuy'] = False
    for i in range(len(df) - 1):
        if df.loc[i, 'signal'] == True:
            df.loc[i + 1, 'openbuy'] = True
    
    return df

In [10]:
conditions(df)

,Close_Time,Open,Close,High,Low,Volume,bb_u,bb_m,bb_l,rsi,slowk,slowd,c1,c2,c3,c4,signal,openbuy
0,2022-01-03 07:59:59.999000064,3765.54,3828.27,3857.44,3717.30,154791.4263,NaN,NaN,NaN,NaN,NaN,NaN,False,False,False,True,False,False
1,2022-01-04 07:59:59.999000064,3828.11,3765.89,3853.09,3680.00,236245.8586,NaN,NaN,NaN,NaN,NaN,NaN,False,False,True,False,False,False
2,2022-01-05 07:59:59.999000064,3765.89,3785.11,3900.73,3713.11,288258.5549,NaN,NaN,NaN,NaN,NaN,NaN,False,True,True,True,False,False
3,2022-01-06 07:59:59.999000064,3785.10,3540.63,3848.00,3415.00,397942.0363,NaN,NaN,NaN,NaN,NaN,NaN,False,False,True,False,False,False
4,2022-01-07 07:59:59.999000064,3539.82,3406.81,3550.43,3300.00,496745.7413,NaN,NaN,NaN,NaN,NaN,NaN,False,False,True,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
406,2023-02-13 07:59:59.999000064,1538.50,1514.83,1548.02,1493.08,286758.3740,1692.521488,1595.751667,1498.981846,44.919076,11.051273,14.301822,True,False,False,False,False,False
407,2023-02-14 07:59:59.999000064,1514.82,1505.24,1526.10,1461.93,643152.3904,1695.097180,1594.263000,1493.428820,43.977097,17.135509,16.592496,True,False,True,False,False,False
408,2023-02-15 07:59:59.999000064,1505.25,1555.71,1569.00,1482.66,668964.3768,1695.033796,1594.369333,1493.704870,49.928268,37.103858,21.763547,True,True,True,True,True,False
409,2023-02-16 07:59:59.999000064,1555.70,1674.92,1680.00,1542.55,581207.8586,1702.111571,1597.635333,1493.159096,60.579947,84.269041,46.169469,False,False,False,True,False,True
410,2023-02-17 07:59:59.999000064,1674.92,1689.35,1712.24,1672.53,294148.1880,1710.534682,1601.761333,1492.987985,61.643604,90.855339,70.742746,False,False,False,True,False,False

In [12]:
buydf = conditions(df)

# 進出場

in_position = False
stop_loss = np.nan

for index, row in buydf.iterrows():

    tp_rsi = 68
    tp_slowk = 80
    tp_slowd = 80
    
    if index == 0:
        continue
        
        # set entry price (前一根Ｋ收盤價進場)
        # set stop loss (前一根Ｋ線低點停損)
        # 進場
    elif buydf.at[index, 'openbuy'] == True:
        close_val = buydf['Close']
        low_val = buydf['Low']
        buydf.at[index, 'entry_p'] = close_val.shift(1).at[index]
        buydf.at[index, 'stop_loss'] = low_val.shift(1).at[index]
        buydf.at[index, 'position'] = 'Buy'
        in_position = True
        stop_loss = low_val.shift(1).at[index]
    

    # 吃筍
    #-----------------------------重要-----------------------------
    # 若用 if 寫，則有可能入場馬上吃筍，若用 elif 則一個 iteration 只會執行一次
    elif in_position == True and buydf.at[index, 'Close'] < stop_loss:
        buydf.at[index, 'position'] = 'Stop'
        in_position = False
        stop_loss = np.nan

    # set take profit （RSI > 68 & KD > 80，或 紅Ｋ貫穿布林Ｍ，即刻出場）
    elif in_position == True and ((buydf.at[index, 'rsi'] >= tp_rsi) & (buydf.at[index, 'slowk'] >= tp_slowk) & (buydf.at[index, 'slowd'] >= tp_slowd)):
        buydf.at[index, 'position'] = 'Sell'
        in_position = False
        stop_loss = np.nan
        
    elif in_position == True and ((buydf.at[index, 'Close'] < buydf.at[index, 'bb_m']) & (buydf.at[index, 'Open'] > buydf.at[index, 'bb_m'])):
        buydf.at[index, 'position'] = 'Sell'
        in_position = False
        stop_loss = np.nan

        
# 過濾有訊號或事件發生的Ｋ線
buydf = buydf[(buydf['openbuy'] == True) |
              (buydf['signal'] == True) | 
              (buydf['position'] == 'Buy') |
              (buydf['position'] == 'Sell') |
              (buydf['position'] == 'Stop')]


print(buydf)

                       Close_Time     Open    Close     High      Low  \
53  2022-02-25 07:59:59.999000064  2579.70  2596.20  2740.00  2300.00
54  2022-02-26 07:59:59.999000064  2596.26  2768.49  2834.97  2571.72
60  2022-03-04 07:59:59.999000064  2947.31  2833.99  2970.97  2785.00
71  2022-03-15 07:59:59.999000064  2515.66  2589.41  2609.60  2498.67
72  2022-03-16 07:59:59.999000064  2589.42  2617.73  2669.00  2507.00
84  2022-03-28 07:59:59.999000064  3145.01  3295.65  3299.37  3126.02
106 2022-04-19 07:59:59.999000064  2988.07  3055.56  3069.60  2883.22
107 2022-04-20 07:59:59.999000064  3055.56  3101.77  3131.00  3030.34
113 2022-04-26 07:59:59.999000064  2920.99  3006.62  3025.65  2797.01
114 2022-04-27 07:59:59.999000064  3006.63  2809.67  3039.54  2767.00
118 2022-05-01 07:59:59.999000064  2817.13  2726.66  2841.63  2709.26
119 2022-05-02 07:59:59.999000064  2726.67  2824.81  2849.90  2716.13
120 2022-05-03 07:59:59.999000064  2824.81  2856.54  2894.22  2778.78
122 2022-05-05 07:59:59.999000064  2781.70  2940.64  2965.85  2771.74
123 2022-05-06 07:59:59.999000064  2940.65  2747.97  2954.65  2683.00
124 2022-05-07 07:59:59.999000064  2747.96  2692.85  2758.18  2632.95
137 2022-05-20 07:59:59.999000064  1915.11  2019.55  2040.39  1903.18
138 2022-05-21 07:59:59.999000064  2019.55  1959.08  2064.00  1923.00
144 2022-05-27 07:59:59.999000064  1942.64  1792.23  1966.01  1735.00
164 2022-06-16 07:59:59.999000064  1208.90  1237.52  1250.00  1014.40
165 2022-06-17 07:59:59.999000064  1237.53  1068.50  1257.85  1051.55
167 2022-06-19 07:59:59.999000064  1086.93   995.13  1097.58   881.56
192 2022-07-14 07:59:59.999000064  1038.58  1115.00  1119.18  1006.32
193 2022-07-15 07:59:59.999000064  1115.01  1193.42  1214.65  1072.11
197 2022-07-19 07:59:59.999000064  1338.65  1581.04  1597.47  1336.07
239 2022-08-30 07:59:59.999000064  1426.76  1551.80  1559.99  1422.08
240 2022-08-31 07:59:59.999000064  1551.79  1524.59  1606.13  1473.61
254 2022-09-14 07:59:59.999000064  1716.37  1574.40  1760.51  1560.54
260 2022-09-20 07:59:59.999000064  1334.51  1375.98  1393.35  1280.00
261 2022-09-21 07:59:59.999000064  1375.98  1322.93  1384.78  1312.71
262 2022-09-22 07:59:59.999000064  1322.94  1245.78  1408.90  1220.00
267 2022-09-27 07:59:59.999000064  1294.62  1336.17  1340.42  1277.85
268 2022-09-28 07:59:59.999000064  1336.17  1328.02  1400.00  1303.75
269 2022-09-29 07:59:59.999000064  1328.01  1337.20  1355.70  1253.20
270 2022-09-30 07:59:59.999000064  1337.20  1335.70  1352.02  1288.52
274 2022-10-04 07:59:59.999000064  1276.72  1323.09  1329.90  1263.04
275 2022-10-05 07:59:59.999000064  1323.10  1361.49  1369.55  1318.66
287 2022-10-17 07:59:59.999000064  1274.93  1305.95  1315.35  1274.67
288 2022-10-18 07:59:59.999000064  1305.96  1331.40  1338.57  1295.64
289 2022-10-19 07:59:59.999000064  1331.39  1310.71  1341.73  1286.72
292 2022-10-22 07:59:59.999000064  1282.57  1299.75  1306.97  1252.65
293 2022-10-23 07:59:59.999000064  1299.76  1313.61  1320.20  1294.32
297 2022-10-27 07:59:59.999000064  1459.74  1566.10  1594.99  1457.44
316 2022-11-15 07:59:59.999000064  1221.50  1243.28  1291.20  1171.13
317 2022-11-16 07:59:59.999000064  1243.29  1253.23  1291.00  1234.01
322 2022-11-21 07:59:59.999000064  1217.67  1142.21  1227.07  1132.65
331 2022-11-30 07:59:59.999000064  1167.77  1216.49  1228.37  1158.27
332 2022-12-01 07:59:59.999000064  1216.49  1294.46  1309.77  1212.50
333 2022-12-02 07:59:59.999000064  1294.46  1276.41  1299.90  1262.77
352 2022-12-21 07:59:59.999000064  1167.82  1216.94  1230.47  1163.12
353 2022-12-22 07:59:59.999000064  1216.95  1213.78  1223.39  1203.02
354 2022-12-23 07:59:59.999000064  1213.78  1217.71  1237.99  1182.54
355 2022-12-24 07:59:59.999000064  1217.72  1219.99  1231.99  1210.00
373 2023-01-11 07:59:59.999000064  1320.40  1335.62  1347.69  1316.80
408 2023-02-15 07:59:59.999000064  1505.25  1555.71  1569.00  1482.66
409 2023-02-16 07:59:59.999000064  1555.70  1674.92  1680.00  1542.55

           Volume         bb_u         bb_m         bb_l        rsi  ...  \
53   1.395733e+06  3275.900757  2817.049000  2358.197243  39.256782  ...
54   6.793942e+05  3267.380218  2827.232333  2387.084449  47.298877  ...
60   4.461922e+05  3259.865256  2874.842667  2489.820077  49.733868  ...
71   3.866302e+05  3088.884109  2728.574667  2368.265225  45.361718  ...
72   4.612023e+05  3078.549695  2720.128000  2361.706305  46.652720  ...
84   3.354674e+05  3228.274936  2801.622667  2374.970398  70.195166  ...
106  5.102517e+05  3551.562075  3183.318333  2815.074592  47.232072  ...
107  3.593750e+05  3541.208549  3191.331333  2841.454118  49.605153  ...
113  6.191984e+05  3546.962707  3178.967667  2810.972626  46.633520  ...
114  5.311844e+05  3551.020154  3162.768333  2774.516513  37.611978  ...
118  3.677572e+05  3508.081591  3095.066667  2682.051743  36.628679  ...
119  4.425449e+05  3475.625012  3074.053333  2672.481655  42.357915  ...
120  5.217069e+05  3438.939765  3054.479000  2670.018235  44.116849  ...
122  5.487381e+05  3316.714472  3010.510000  2704.305528  49.286719  ...
123  7.348453e+05  3271.494438  2988.542667  2705.590895  41.612071  ...
124  7.114493e+05  3266.618607  2972.687333  2678.756060  39.707149  ...
137  7.414770e+05  3346.199747  2564.596000  1782.992253  35.523695  ...
138  5.769815e+05  3314.364308  2527.364000  1740.363692  34.046007  ...
144  1.168741e+06  3103.529539  2330.349333  1557.169128  31.001398  ...
164  3.114823e+06  2253.177630  1784.760667  1316.343703  23.434182  ...
165  1.447387e+06  2270.968064  1750.686667  1230.405269  19.936585  ...
167  2.308984e+06  2302.979864  1688.933667  1074.887470  19.513265  ...
192  2.035606e+06  1270.796779  1136.847667  1002.898555  42.348127  ...
193  1.605102e+06  1269.282102  1136.331667  1003.381231  48.659002  ...
197  2.029919e+06  1389.501464  1173.621667   957.741869  68.835939  ...
239  8.262521e+05  1995.209435  1708.761000  1422.312565  44.382766  ...
240  1.003075e+06  1997.489022  1703.643333  1409.797645  42.939351  ...
254  1.134550e+06  1872.956745  1641.581333  1410.205921  45.165699  ...
260  9.748552e+05  1790.390317  1577.679333  1364.968350  38.036543  ...
261  6.580271e+05  1798.693087  1567.839333  1336.985580  35.710307  ...
262  1.192267e+06  1812.220905  1555.210000  1298.199095  32.588852  ...
267  7.991664e+05  1804.080765  1508.054000  1212.027235  40.578564  ...
268  8.605849e+05  1806.472767  1504.762667  1203.052566  40.103613  ...
269  9.193149e+05  1804.648314  1497.609333  1190.570353  40.942108  ...
270  7.705917e+05  1803.583049  1491.313000  1179.042951  40.841499  ...
274  4.837752e+05  1784.389711  1456.888000  1129.386289  41.906222  ...
275  4.762077e+05  1775.607918  1449.628333  1123.648749  45.948629  ...
287  2.933214e+05  1399.735989  1321.839000  1243.942011  44.199138  ...
288  4.598485e+05  1373.073230  1317.258000  1261.442770  48.164283  ...
289  5.727289e+05  1371.952097  1316.464667  1260.977236  45.343372  ...
292  4.680768e+05  1361.111175  1313.888667  1266.666158  44.823202  ...
293  2.217767e+05  1360.451503  1313.460333  1266.469164  47.249930  ...
297  1.236045e+06  1442.578168  1328.742667  1214.907165  72.107683  ...
316  9.347420e+05  1714.903908  1416.597667  1118.291425  40.785508  ...
317  6.328256e+05  1716.337275  1414.840333  1113.343391  41.514351  ...
322  5.311088e+05  1733.526653  1397.491667  1061.456680  35.837791  ...
331  5.121436e+05  1648.052916  1307.242333   966.431751  45.999887  ...
332  8.156793e+05  1624.211146  1297.968000   971.724854  53.439290  ...
333  4.300187e+05  1597.090558  1287.899000   978.707442  51.664804  ...
352  4.651842e+05  1337.045207  1231.034667  1125.024127  46.794943  ...
353  2.457238e+05  1330.434263  1234.582667  1138.731071  46.443999  ...
354  3.367617e+05  1326.603760  1237.186333  1147.768907  46.976594  ...
355  2.786043e+05  1325.887125  1238.368667  1150.850208  47.304006  ...
373  4.596602e+05  1325.776863  1234.170333  1142.563804  69.112661  ...
408  6.689644e+05  1695.033796  1594.369333  1493.704870  49.928268  ...
409  5.812079e+05  1702.111571  1597.635333  1493.159096  60.579947  ...

         slowd     c1     c2     c3     c4  signal  openbuy  entry_p  \
53   20.204667   True   True   True   True    True    False      NaN
54   31.832758   True  False  False   True   False     True  2596.20
60   74.439302   True  False  False  False   False    False      NaN
71   18.859818   True   True   True   True    True    False      NaN
72   21.583098   True  False   True   True   False     True  2589.41
84   93.208742  False  False   True   True   False    False      NaN
106  16.428330   True   True   True   True    True    False      NaN
107  24.543627   True  False  False   True   False     True  3055.56
113  25.970603   True   True   True   True    True    False      NaN
114  25.498629   True  False  False  False   False     True  3006.62
118  18.993200   True  False  False  False   False    False      NaN
119  13.460260   True   True   True   True    True    False      NaN
120  19.843226   True  False   True   True   False     True  2824.81
122  31.942615   True   True   True   True    True    False      NaN
123  27.587765   True  False   True  False   False     True  2940.64
124  27.369014   True  False  False  False   False    False      NaN
137  19.272933   True   True   True   True    True    False      NaN
138  16.824275   True  False  False  False   False     True  2019.55
144  25.633344   True  False   True  False   False    False      NaN
164  14.897888   True   True   True   True    True    False      NaN
165  15.151246   True  False  False  False   False     True  1237.52
167   8.306899   True  False   True  False   False    False      NaN
192  30.642342   True   True   True   True    True    False      NaN
193  41.950066  False  False  False   True   False     True  1115.00
197  86.965729  False   True   True   True   False    False      NaN
239  10.694879   True   True   True   True    True    False      NaN
240  14.562218   True  False   True  False   False     True  1551.80
254  66.267199   True  False   True  False   False    False      NaN
260  12.433081   True   True   True   True    True    False      NaN
261   9.741364   True  False  False  False   False     True  1375.98
262  10.607174   True  False   True  False   False    False      NaN
267  17.272912   True   True   True   True    True    False      NaN
268  19.856403   True  False   True  False   False     True  1336.17
269  24.414528   True   True   True   True    True    False      NaN
270  31.894949   True  False  False  False   False     True  1337.20
274  40.456913   True   True   True   True    True    False      NaN
275  53.167461   True  False  False   True   False     True  1323.09
287  52.775916   True   True   True   True    True    False      NaN
288  58.812310  False  False   True   True   False     True  1305.95
289  64.962111   True  False   True  False   False    False      NaN
292  58.197303   True   True   True   True    True    False      NaN
293  68.767150  False  False  False   True   False     True  1299.75
297  85.985918  False  False   True   True   False    False      NaN
316  27.560033   True   True   True   True    True    False      NaN
317  27.339082   True  False  False   True   False     True  1243.28
322  20.589910   True  False   True  False   False    False      NaN
331  56.997487   True   True   True   True    True    False      NaN
332  69.828353   True  False   True   True   False     True  1216.49
333  84.108778   True  False  False  False   False    False      NaN
352  18.488359   True   True   True   True    True    False      NaN
353  24.233882   True  False  False  False   False     True  1216.94
354  32.458006   True   True   True   True    True    False      NaN
355  32.960783   True  False  False   True   False     True  1217.71
373  90.903529  False  False  False   True   False    False      NaN
408  21.763547   True   True   True   True    True    False      NaN
409  46.169469  False  False  False   True   False     True  1555.71

     stop_loss  position
53         NaN       NaN
54     2300.00       Buy
60         NaN      Sell
71         NaN       NaN
72     2498.67       Buy
84         NaN      Sell
106        NaN       NaN
107    2883.22       Buy
113        NaN       NaN
114    2797.01       Buy
118        NaN      Stop
119        NaN       NaN
120    2716.13       Buy
122        NaN       NaN
123    2771.74       Buy
124        NaN      Stop
137        NaN       NaN
138    1903.18       Buy
144        NaN      Stop
164        NaN       NaN
165    1014.40       Buy
167        NaN      Stop
192        NaN       NaN
193    1006.32       Buy
197        NaN      Sell
239        NaN       NaN
240    1422.08       Buy
254        NaN      Sell
260        NaN       NaN
261    1280.00       Buy
262        NaN      Stop
267        NaN       NaN
268    1277.85       Buy
269        NaN       NaN
270    1253.20       Buy
274        NaN       NaN
275    1263.04       Buy
287        NaN       NaN
288    1274.67       Buy
289        NaN      Sell
292        NaN       NaN
293    1252.65       Buy
297        NaN      Sell
316        NaN       NaN
317    1171.13       Buy
322        NaN      Stop
331        NaN       NaN
332    1158.27       Buy
333        NaN      Sell
352        NaN       NaN
353    1163.12       Buy
354        NaN       NaN
355    1182.54       Buy
373        NaN      Sell
408        NaN       NaN
409    1482.66       Buy

[56 rows x 21 columns]

In [13]:
# 部位回測

posdf = buydf
posdf = posdf.reset_index(drop = True)
posdf = posdf[(posdf['position'] == 'Buy') |
              (posdf['position'] == 'Sell') |
              (posdf['position'] == 'Stop')]

# 一次進場多少單位
pos_size = 1

col = ['Close_Time', 'Open', 'Close', 'High', 'Low', 'bb_u', 'bb_l', 'rsi', 'slowk', 'slowd', 'position','entry_p', 'stop_loss']
pos = posdf[col]
pos = pos.reset_index(drop = True)


for index, row in pos.iterrows():
    
    current_pos = 0
    
    # 進場
    if pos.at[index, 'position'] == 'Buy':
        pos.at[index, 'size'] = pos_size
        pos.exit_p = np.nan
    
    # 出場
    if pos.at[index, 'position'] == 'Sell' or pos.at[index, 'position'] == 'Stop':
        
        #-----------------------------重要-----------------------------
        # 實戰需即刻出場
        
        # 停利：RSI > 68 & KD > 80，出場價設定為該日收盤
        if pos.at[index, 'position'] == 'Sell':
            pos.at[index, 'exit_p'] = pos.at[index, 'Close'] * 1

        # 停損：打到進場停損點（往回跌代，直到最近的'Buy'及其'stop_loss'）
        if pos.at[index, 'position'] == 'Stop':
            for i in range(index -1, -1, -1):
                if pos.at[i, 'position'] == 'Buy':
                    pos.at[index, 'exit_p'] = pos.at[i, 'stop_loss']
                break

        # 計算每次出場部位大小（每次出場皆清倉）
        for i in range(index -1, -1, -1):
            if pos.at[i, 'position'] == 'Buy':
                current_pos += pos.at[i, 'size']
                if i == 0:
                    pos.at[index, 'size'] = -current_pos
                else:
                    continue
            else:
                pos.at[index, 'size'] = -current_pos
                current_pos = 0
                break


# 計算部位價值
for index, row in pos.iterrows():
    if pos.at[index, 'position'] == 'Buy':
        pos.at[index, 'amt'] = round(pos.at[index, 'size'] * pos.at[index, 'entry_p'], 4)
    elif pos.at[index, 'position'] == 'Sell' or pos.at[index, 'position'] == 'Stop':
        pos.at[index, 'amt'] = round(pos.at[index, 'size'] * pos.at[index, 'exit_p'], 4)

        
# 若最後一筆為 Buy，移除該單，迭代驗證
for index, row in pos.iloc[::-1].iterrows():
    if row['position'] == 'Buy':
        pos = pos.drop(index)
    else:
        break
    
        
print(pos)
pos.to_csv('pos.csv')


# 手續費、滑點、價差
fee = 0.075 / 100
amt_abs_sum = pos.amt.abs().sum()
ttl_fee = amt_abs_sum * fee

# 損益
leverage = 10
ttl_profit = -pos.amt.sum() - ttl_fee


# 計算進場最大部位來代表總進場成本，以計算報酬率
pos['consec_entry'] = (pos['position'] != pos['position'].shift()).cumsum()
group_consec = pos.groupby('consec_entry').apply(lambda x:x.loc[x['position'] == 'Buy', 'amt' ].sum())
max_entry = group_consec.max()

profit_per = "{:.2f}%".format(ttl_profit / (max_entry/leverage) * 100)


result = {'Profit': [round(ttl_profit, 2)],
          'Fee': [round(ttl_fee, 2)],
          'Max_Entry': [round(max_entry, 2)],
          'Profit_%': [profit_per]}

result_df = pd.DataFrame(result)

print(result_df)

                      Close_Time     Open    Close     High      Low  \
0  2022-02-26 07:59:59.999000064  2596.26  2768.49  2834.97  2571.72
1  2022-03-04 07:59:59.999000064  2947.31  2833.99  2970.97  2785.00
2  2022-03-16 07:59:59.999000064  2589.42  2617.73  2669.00  2507.00
3  2022-03-28 07:59:59.999000064  3145.01  3295.65  3299.37  3126.02
4  2022-04-20 07:59:59.999000064  3055.56  3101.77  3131.00  3030.34
5  2022-04-27 07:59:59.999000064  3006.63  2809.67  3039.54  2767.00
6  2022-05-01 07:59:59.999000064  2817.13  2726.66  2841.63  2709.26
7  2022-05-03 07:59:59.999000064  2824.81  2856.54  2894.22  2778.78
8  2022-05-06 07:59:59.999000064  2940.65  2747.97  2954.65  2683.00
9  2022-05-07 07:59:59.999000064  2747.96  2692.85  2758.18  2632.95
10 2022-05-21 07:59:59.999000064  2019.55  1959.08  2064.00  1923.00
11 2022-05-27 07:59:59.999000064  1942.64  1792.23  1966.01  1735.00
12 2022-06-17 07:59:59.999000064  1237.53  1068.50  1257.85  1051.55
13 2022-06-19 07:59:59.999000064  1086.93   995.13  1097.58   881.56
14 2022-07-15 07:59:59.999000064  1115.01  1193.42  1214.65  1072.11
15 2022-07-19 07:59:59.999000064  1338.65  1581.04  1597.47  1336.07
16 2022-08-31 07:59:59.999000064  1551.79  1524.59  1606.13  1473.61
17 2022-09-14 07:59:59.999000064  1716.37  1574.40  1760.51  1560.54
18 2022-09-21 07:59:59.999000064  1375.98  1322.93  1384.78  1312.71
19 2022-09-22 07:59:59.999000064  1322.94  1245.78  1408.90  1220.00
20 2022-09-28 07:59:59.999000064  1336.17  1328.02  1400.00  1303.75
21 2022-09-30 07:59:59.999000064  1337.20  1335.70  1352.02  1288.52
22 2022-10-05 07:59:59.999000064  1323.10  1361.49  1369.55  1318.66
23 2022-10-18 07:59:59.999000064  1305.96  1331.40  1338.57  1295.64
24 2022-10-19 07:59:59.999000064  1331.39  1310.71  1341.73  1286.72
25 2022-10-23 07:59:59.999000064  1299.76  1313.61  1320.20  1294.32
26 2022-10-27 07:59:59.999000064  1459.74  1566.10  1594.99  1457.44
27 2022-11-16 07:59:59.999000064  1243.29  1253.23  1291.00  1234.01
28 2022-11-21 07:59:59.999000064  1217.67  1142.21  1227.07  1132.65
29 2022-12-01 07:59:59.999000064  1216.49  1294.46  1309.77  1212.50
30 2022-12-02 07:59:59.999000064  1294.46  1276.41  1299.90  1262.77
31 2022-12-22 07:59:59.999000064  1216.95  1213.78  1223.39  1203.02
32 2022-12-24 07:59:59.999000064  1217.72  1219.99  1231.99  1210.00
33 2023-01-11 07:59:59.999000064  1320.40  1335.62  1347.69  1316.80

           bb_u         bb_l        rsi      slowk      slowd position  \
0   3267.380218  2387.084449  47.298877  52.275745  31.832758      Buy
1   3259.865256  2489.820077  49.733868  71.781533  74.439302     Sell
2   3078.549695  2361.706305  46.652720  28.840727  21.583098      Buy
3   3228.274936  2374.970398  70.195166  99.535407  93.208742     Sell
4   3541.208549  2841.454118  49.605153  41.685740  24.543627      Buy
5   3551.020154  2774.516513  37.611978  10.331719  25.498629      Buy
6   3508.081591  2682.051743  36.628679   3.696308  18.993200     Stop
7   3438.939765  2670.018235  44.116849  31.286910  19.843226      Buy
8   3271.494438  2705.590895  41.612071  18.222359  27.587765      Buy
9   3266.618607  2678.756060  39.707149  14.732286  27.369014     Stop
10  3314.364308  1740.363692  34.046007  17.590340  16.824275      Buy
11  3103.529539  1557.169128  31.001398  13.247685  25.633344     Stop
12  2270.968064  1230.405269  19.936585   5.973940  15.151246      Buy
13  2302.979864  1074.887470  19.513265  10.936597   8.306899     Stop
14  1269.282102  1003.381231  48.659002  69.260384  41.950066      Buy
15  1389.501464   957.741869  68.835939  97.220672  86.965729     Sell
16  1997.489022  1409.797645  42.939351  19.076952  14.562218      Buy
17  1872.956745  1410.205921  45.165699  28.068647  66.267199     Sell
18  1798.693087  1336.985580  35.710307   8.434185   9.741364      Buy
19  1812.220905  1298.199095  32.588852   4.530756  10.607174     Stop
20  1806.472767  1203.052566  40.103613  24.820772  19.856403      Buy
21  1803.583049  1179.042951  40.841499  43.933928  31.894949      Buy
22  1775.607918  1123.648749  45.948629  74.902065  53.167461      Buy
23  1373.073230  1261.442770  48.164283  72.890355  58.812310      Buy
24  1371.952097  1260.977236  45.343372  62.224857  64.962111     Sell
25  1360.451503  1266.469164  47.249930  80.727534  68.767150      Buy
26  1442.578168  1214.907165  72.107683  92.866491  85.985918     Sell
27  1716.337275  1113.343391  41.514351  29.630485  27.339082      Buy
28  1733.526653  1061.456680  35.837791  12.849152  20.589910     Stop
29  1624.211146   971.724854  53.439290  93.478724  69.828353      Buy
30  1597.090558   978.707442  51.664804  85.790348  84.108778     Sell
31  1330.434263  1138.731071  46.443999  31.289254  24.233882      Buy
32  1325.887125  1150.850208  47.304006  34.360318  32.960783      Buy
33  1325.776863  1142.563804  69.112661  92.756406  90.903529     Sell

    entry_p  stop_loss  size   exit_p      amt
0   2596.20    2300.00   1.0      NaN  2596.20
1       NaN        NaN  -1.0  2833.99 -2833.99
2   2589.41    2498.67   1.0      NaN  2589.41
3       NaN        NaN  -1.0  3295.65 -3295.65
4   3055.56    2883.22   1.0      NaN  3055.56
5   3006.62    2797.01   1.0      NaN  3006.62
6       NaN        NaN  -2.0  2797.01 -5594.02
7   2824.81    2716.13   1.0      NaN  2824.81
8   2940.64    2771.74   1.0      NaN  2940.64
9       NaN        NaN  -2.0  2771.74 -5543.48
10  2019.55    1903.18   1.0      NaN  2019.55
11      NaN        NaN  -1.0  1903.18 -1903.18
12  1237.52    1014.40   1.0      NaN  1237.52
13      NaN        NaN  -1.0  1014.40 -1014.40
14  1115.00    1006.32   1.0      NaN  1115.00
15      NaN        NaN  -1.0  1581.04 -1581.04
16  1551.80    1422.08   1.0      NaN  1551.80
17      NaN        NaN  -1.0  1574.40 -1574.40
18  1375.98    1280.00   1.0      NaN  1375.98
19      NaN        NaN  -1.0  1280.00 -1280.00
20  1336.17    1277.85   1.0      NaN  1336.17
21  1337.20    1253.20   1.0      NaN  1337.20
22  1323.09    1263.04   1.0      NaN  1323.09
23  1305.95    1274.67   1.0      NaN  1305.95
24      NaN        NaN  -4.0  1310.71 -5242.84
25  1299.75    1252.65   1.0      NaN  1299.75
26      NaN        NaN  -1.0  1566.10 -1566.10
27  1243.28    1171.13   1.0      NaN  1243.28
28      NaN        NaN  -1.0  1171.13 -1171.13
29  1216.49    1158.27   1.0      NaN  1216.49
30      NaN        NaN  -1.0  1276.41 -1276.41
31  1216.94    1163.12   1.0      NaN  1216.94
32  1217.71    1182.54   1.0      NaN  1217.71
33      NaN        NaN  -2.0  1335.62 -2671.24
   Profit    Fee  Max_Entry Profit_%
0  683.94  54.27    6062.18  112.82%

In [ ]:
plt.title(symbol + ' SMA_' + str(rate))
plt.xlabel('time')
plt.ylabel('Closing Prices')
plt.plot(df.Close, label='Closing Prices')
plt.plot(df.sma, label= str(rate) + ' SMA')
plt.plot(df.bb_u, label='Bollinger Up', c='g')
plt.plot(df.bb_l, label='Bollinger Down', c='r')
plt.legend()
plt.show()