In [1]:
# start time - 1609459200000, 1641028611000, 1672564611000, 1654045261000, 1651366861000 (2021, 2022, 2023)

In [2]:
# ! conda install -c conda-forge ta --yes

In [3]:
import requests
import pandas as pd
import ta
import datetime as dt
import numpy as np
import time
import itertools
import os

In [4]:
from binance.client import Client
from dotenv import load_dotenv

# Get the path to the current directory
current_directory = os.getcwd()

# Specify the path to the .env file relative to the current directory
dotenv_path = os.path.join(current_directory, '.env')

# Load the environment variables from the .env file
load_dotenv(dotenv_path)

api_key = os.getenv('API_KEY')
api_secret = os.getenv('SECRET_KEY')

client = Client(api_key, api_secret, testnet = False)

In [5]:
interval_arr = ['1h', '4h']
ema_arr = [8, 18, 38]

ep_per_arr = [1.005, 0.999, 0.995, 0.990]

sl_per_arr = [0.999, 1.003, 1.007, 1.011]

# stop loss determine candlestick
sl_det_arr = ['Close', 'High']

In [6]:
timezone = 8
# symbol = 'ethusdt'
symbol_arr = ['ethusdt', 'crvusdt', 'injusdt', 'imxusdt', 'roseusdt', 'linausdt', 'ftmusdt', 'adausdt', 'avaxusdt']

start_time = 1635743450000
end_time = round(time.time() * 1000)

def set_time():
    global start_time, end_time
    start_time = 1635743450000
    end_time = round(time.time() * 1000)

# step between timestamps in milliseconds
step = 1000

In [7]:
dataframes = {}
def create_raw(symbol_arr, interval_arr, step):
    global start_time, end_time
    
    for interval in interval_arr:
        for symbol in symbol_arr:
            set_time()
            # Fetch the data using batch requests
            data = []
            while start_time < end_time:
                limit = min(step, end_time - start_time + 1)  # Adjust the limit for the last batch
                response = client.get_klines(symbol=symbol.upper(), interval=interval, limit=limit, startTime=start_time)

                if len(response) == 0:
                    break  # No more data available, exit the loop
                data.extend(response)
                start_time = response[-1][0] + 1

            # Convert the data to a DataFrame
            columns = [
                "Open_Time", "Open", "High", "Low", "Close", "Volume", "Close_Time",
                "Quote asset volume", "Number of trades", "Taker buy base asset volume",
                "Taker buy quote asset volume", "Ignore"
            ]
            raw_df = pd.DataFrame(data, columns=columns)   

            raw_df = raw_df[['Open_Time', 'Open', 'Close', "High", "Low", 'Volume']]

            dataframes[f'df_{interval}_{symbol}'] = raw_df

In [8]:
loop_start_time = time.time()
create_raw(symbol_arr, interval_arr, step)
loop_end_time = time.time()
print("Time taken to execute for loop:", loop_end_time - loop_start_time, "seconds")
print(dataframes)

Time taken to execute for loop: 17.788798809051514 seconds
{'df_1h_ethusdt':            Open_Time           Open          Close           High  \
0      1635746400000  4225.00000000  4241.99000000  4259.14000000
1      1635750000000  4241.99000000  4302.93000000  4320.00000000
2      1635753600000  4302.94000000  4311.11000000  4338.07000000
3      1635757200000  4311.11000000  4316.56000000  4344.41000000
4      1635760800000  4316.55000000  4328.94000000  4335.00000000
...              ...            ...            ...            ...
14033  1686268800000  1845.65000000  1843.79000000  1846.87000000
14034  1686272400000  1843.80000000  1842.81000000  1849.02000000
14035  1686276000000  1842.80000000  1835.75000000  1844.34000000
14036  1686279600000  1835.75000000  1838.23000000  1838.64000000
14037  1686283200000  1838.22000000  1837.44000000  1838.23000000

                 Low          Volume
0      4198.55000000  13908.93710000
1      4241.46000000  31363.21900000
2      4294.52000000  21038.55420000
3      4310.64000000  16175.35920000
4      4313.86000000  11207.71110000
...              ...             ...
14033  1843.00000000   3931.50910000
14034  1842.50000000   6365.37020000
14035  1827.00000000  26334.77110000
14036  1832.05000000   7337.86440000
14037  1837.41000000    342.53200000

[14038 rows x 6 columns], 'df_1h_crvusdt':            Open_Time        Open       Close        High         Low  \
0      1635746400000  4.30100000  4.32600000  4.35300000  4.27000000
1      1635750000000  4.32700000  4.39400000  4.41700000  4.32700000
2      1635753600000  4.39500000  4.37600000  4.43600000  4.34700000
3      1635757200000  4.37600000  4.36600000  4.40500000  4.36200000
4      1635760800000  4.36500000  4.40400000  4.46100000  4.36500000
...              ...         ...         ...         ...         ...
14033  1686268800000  0.76100000  0.75700000  0.76100000  0.75700000
14034  1686272400000  0.75700000  0.75900000  0.76200000  0.75700000
14035  1686276000000  0.75900000  0.75500000  0.76000000  0.75100000
14036  1686279600000  0.75500000  0.75800000  0.75900000  0.75200000
14037  1686283200000  0.75900000  0.75800000  0.75900000  0.75800000

                Volume
0      303124.40000000
1      601910.40000000
2      380985.90000000
3      422365.00000000
4      651086.50000000
...                ...
14033  131880.00000000
14034   95627.50000000
14035  437625.10000000
14036  152087.00000000
14037     224.90000000

[14038 rows x 6 columns], 'df_1h_injusdt':            Open_Time         Open        Close         High          Low  \
0      1635746400000  10.71800000  10.71400000  10.73400000  10.67000000
1      1635750000000  10.71500000  10.87600000  10.87600000  10.71500000
2      1635753600000  10.87600000  10.92200000  10.94000000  10.86400000
3      1635757200000  10.93100000  11.02400000  11.35000000  10.92600000
4      1635760800000  11.01000000  11.07900000  11.10700000  11.00100000
...              ...          ...          ...          ...          ...
14033  1686268800000   6.94500000   6.95000000   6.98000000   6.93100000
14034  1686272400000   6.94700000   7.01200000   7.04200000   6.92700000
14035  1686276000000   7.00800000   6.90200000   7.01100000   6.88900000
14036  1686279600000   6.89400000   6.91200000   6.96900000   6.86200000
14037  1686283200000   6.91400000   6.90000000   6.91400000   6.89900000

               Volume
0       7908.40000000
1      14399.30000000
2      14244.90000000
3      66909.20000000
4      12787.60000000
...               ...
14033  36266.80000000
14034  44868.50000000
14035  60735.30000000
14036  52055.20000000
14037   1261.00000000

[14038 rows x 6 columns], 'df_1h_imxusdt':            Open_Time        Open       Close        High         Low  \
0      1641808800000  3.75100000  3.84500000  4.30000000  3.75100000
1      1641812400000  3.84500000  3.73200000  3.88300000  3.71300000
2      1641816000000  3.72900000  3.61100000  3.79900000  3.58400000
3      1641819600000  3.61000000  3.57200000  3.64600000  3.55300000
4      1641823200000  3.57200000  3.57800000  3.66400000  3.41900000
...              ...         ...         ...         ...         ...
12349  1686268800000  0.71600000  0.71800000  0.72300000  0.71400000
12350  1686272400000  0.71800000  0.72700000  0.73600000  0.71600000
12351  1686276000000  0.72700000  0.72000000  0.73400000  0.71800000
12352  1686279600000  0.72000000  0.72500000  0.73000000  0.72000000
12353  1686283200000  0.72500000  0.72400000  0.72500000  0.72400000

                 Volume
0      1020857.48000000
1       223323.22000000
2       135615.70000000
3        96669.22000000
4       285832.48000000
...                 ...
12349   138050.65000000
12350   333443.80000000
12351   342104.38000000
12352   145565.92000000
12353     4799.64000000

[12354 rows x 6 columns], 'df_1h_roseusdt':            Open_Time        Open       Close        High         Low  \
0      1635746400000  0.18050000  0.18251000  0.18251000  0.17987000
1      1635750000000  0.18251000  0.18325000  0.18507000  0.18240000
2      1635753600000  0.18320000  0.18277000  0.18498000  0.18269000
3      1635757200000  0.18277000  0.18313000  0.18400000  0.18250000
4      1635760800000  0.18313000  0.18578000  0.18650000  0.18285000
...              ...         ...         ...         ...         ...
14033  1686268800000  0.04998000  0.04998000  0.05035000  0.04993000
14034  1686272400000  0.04999000  0.05032000  0.05049000  0.04998000
14035  1686276000000  0.05031000  0.05000000  0.05031000  0.04962000
14036  1686279600000  0.04996000  0.05019000  0.05027000  0.04994000
14037  1686283200000  0.05018000  0.05022000  0.05022000  0.05018000

                 Volume
0      1298209.80000000
1      3131338.70000000
2      1455666.70000000
3      2060363.60000000
4      2571658.60000000
...                 ...
14033  1334598.10000000
14034  1349841.20000000
14035  2190789.50000000
14036   941789.70000000
14037    14757.30000000

[14038 rows x 6 columns], 'df_1h_linausdt':            Open_Time        Open       Close        High         Low  \
0      1635746400000  0.05050000  0.05082000  0.05129000  0.05006000
1      1635750000000  0.05086000  0.05220000  0.05254000  0.05086000
2      1635753600000  0.05218000  0.05191000  0.05269000  0.05171000
3      1635757200000  0.05195000  0.05319000  0.05391000  0.05180000
4      1635760800000  0.05317000  0.05206000  0.05329000  0.05142000
...              ...         ...         ...         ...         ...
14033  1686268800000  0.01242500  0.01238700  0.01266000  0.01236300
14034  1686272400000  0.01239100  0.01254000  0.01268100  0.01237400
14035  1686276000000  0.01253700  0.01237100  0.01253700  0.01230400
14036  1686279600000  0.01237500  0.01245900  0.01266900  0.01236300
14037  1686283200000  0.01245900  0.01247200  0.01247900  0.01244700

                  Volume
0       7372147.72000000
1      13751771.09000000
2      10534965.93000000
3      25149411.66000000
4      22133891.08000000
...                  ...
14033  70205157.84000000
14034  53902687.50000000
14035  67048251.44000000
14036  47899668.63000000
14037   1553958.78000000

[14038 rows x 6 columns], 'df_1h_ftmusdt':            Open_Time        Open       Close        High         Low  \
0      1635746400000  2.81940000  2.81500000  2.87860000  2.79190000
1      1635750000000  2.81620000  2.86700000  2.91000000  2.81490000
2      1635753600000  2.86640000  2.83380000  2.89540000  2.82900000
3      1635757200000  2.83350000  2.85750000  2.87000000  2.83010000
4      1635760800000  2.85750000  2.81500000  2.86100000  2.81500000
...              ...         ...         ...         ...         ...
14033  1686268800000  0.29580000  0.29390000  0.29640000  0.29360000
14034  1686272400000  0.29380000  0.29460000  0.29750000  0.29320000
14035  1686276000000  0.29450000  0.29150000  0.29490000  0.29020000
14036  1686279600000  0.29150000  0.29320000  0.29350000  0.29060000
14037  1686283200000  0.29330000  0.29300000  0.29330000  0.29290000

                 Volume
0      5023525.00000000
1      4723813.00000000
2      3347471.00000000
3      3021817.00000000
4      3293481.00000000
...                 ...
14033  3015255.00000000
14034  2903688.00000000
14035  4471543.00000000
14036  1777155.00000000
14037    62149.00000000

[14038 rows x 6 columns], 'df_1h_adausdt':            Open_Time        Open       Close        High         Low  \
0      1635746400000  1.93500000  1.94300000  1.94700000  1.92600000
1      1635750000000  1.94200000  1.97800000  1.97800000  1.94000000
2      1635753600000  1.97800000  1.97500000  1.98900000  1.97300000
3      1635757200000  1.97600000  1.99000000  2.01900000  1.97500000
4      1635760800000  1.98900000  1.98500000  1.99500000  1.97900000
...              ...         ...         ...         ...         ...
14033  1686268800000  0.32290000  0.32120000  0.32290000  0.32040000
14034  1686272400000  0.32120000  0.32190000  0.32370000  0.32050000
14035  1686276000000  0.32180000  0.31920000  0.32180000  0.31750000
14036  1686279600000  0.31920000  0.32050000  0.32090000  0.31790000
14037  1686283200000  0.32050000  0.31990000  0.32060000  0.31980000

                  Volume
0       3221200.90000000
1       9139462.20000000
2       9244535.90000000
3      14260170.80000000
4       6143576.40000000
...                  ...
14033   3696385.20000000
14034   3951266.10000000
14035   6975311.50000000
14036   2345072.50000000
14037     90287.20000000

[14038 rows x 6 columns], 'df_1h_avaxusdt':            Open_Time         Open        Close         High          Low  \
0      1635746400000  63.61000000  63.25000000  63.61000000  62.93000000
1      1635750000000  63.25000000  63.85000000  63.95000000  63.24000000
2      1635753600000  63.87000000  63.41000000  64.34000000  63.31000000
3      1635757200000  63.38000000  64.02000000  64.12000000  63.38000000
4      1635760800000  64.01000000  63.98000000  64.21000000  63.72000000
...              ...          ...          ...          ...          ...
14033  1686268800000  13.93000000  13.89000000  13.95000000  13.86000000
14034  1686272400000  13.89000000  13.88000000  13.95000000  13.87000000
14035  1686276000000  13.88000000  13.79000000  13.90000000  13.72000000
14036  1686279600000  13.79000000  13.83000000  13.84000000  13.75000000
14037  1686283200000  13.83000000  13.83000000  13.83000000  13.82000000

                Volume
0       39574.84000000
1       69719.10000000
2       82164.96000000
3       58868.51000000
4       52886.29000000
...                ...
14033   25935.78000000
14034   28358.20000000
14035  129694.77000000
14036   46711.47000000
14037     417.79000000

[14038 rows x 6 columns], 'df_4h_ethusdt':           Open_Time           Open          Close           High  \
0     1635753600000  4302.94000000  4315.00000000  4354.33000000
1     1635768000000  4315.00000000  4349.98000000  4386.58000000
2     1635782400000  4349.97000000  4364.28000000  4366.00000000
3     1635796800000  4364.28000000  4319.43000000  4365.78000000
4     1635811200000  4319.43000000  4318.83000000  4349.89000000
...             ...            ...            ...            ...
3505  1686225600000  1843.79000000  1855.66000000  1861.28000000
3506  1686240000000  1855.67000000  1847.73000000  1856.24000000
3507  1686254400000  1847.73000000  1845.64000000  1854.00000000
3508  1686268800000  1845.65000000  1838.23000000  1849.02000000
3509  1686283200000  1838.22000000  1837.44000000  1838.23000000

                Low          Volume
0     4294.52000000  74210.59030000
1     4308.25000000  74035.47200000
2     4264.63000000  60730.02210000
3     4278.07000000  43891.13250000
4     4284.43000000  42735.69390000
...             ...             ...
3505  1837.86000000  63069.21460000
3506  1841.35000000  25927.23780000
3507  1844.92000000  18475.60000000
3508  1827.00000000  43969.51480000
3509  1837.41000000    347.78340000

[3510 rows x 6 columns], 'df_4h_crvusdt':           Open_Time        Open       Close        High         Low  \
0     1635753600000  4.39500000  4.45200000  4.53200000  4.34700000
1     1635768000000  4.45300000  4.48400000  4.51900000  4.31700000
2     1635782400000  4.48500000  4.40200000  4.49500000  4.28800000
3     1635796800000  4.40000000  4.50800000  4.53900000  4.28900000
4     1635811200000  4.50900000  4.40200000  4.63600000  4.32500000
...             ...         ...         ...         ...         ...
3505  1686225600000  0.75800000  0.76700000  0.77200000  0.75300000
3506  1686240000000  0.76700000  0.76300000  0.76700000  0.75700000
3507  1686254400000  0.76300000  0.76000000  0.76700000  0.75800000
3508  1686268800000  0.76100000  0.75800000  0.76200000  0.75100000
3509  1686283200000  0.75900000  0.75800000  0.75900000  0.75800000

                Volume
0     2441231.40000000
1     3585230.50000000
2     1901628.40000000
3     2219941.50000000
4     3881920.40000000
...                ...
3505  1971119.00000000
3506   761699.50000000
3507   789653.70000000
3508   817219.60000000
3509      224.90000000

[3510 rows x 6 columns], 'df_4h_injusdt':           Open_Time         Open        Close         High          Low  \
0     1635753600000  10.87600000  10.94700000  11.35000000  10.86400000
1     1635768000000  10.95100000  10.87700000  11.03400000  10.79900000
2     1635782400000  10.88100000  10.60300000  10.89600000  10.49600000
3     1635796800000  10.58800000  10.60700000  10.63000000  10.51500000
4     1635811200000  10.60700000  10.56100000  10.62400000  10.49900000
...             ...          ...          ...          ...          ...
3505  1686225600000   6.93400000   7.11500000   7.17200000   6.86400000
3506  1686240000000   7.11400000   7.06000000   7.13800000   6.85000000
3507  1686254400000   7.06800000   6.94100000   7.11200000   6.94000000
3508  1686268800000   6.94500000   6.91200000   7.04200000   6.86200000
3509  1686283200000   6.91400000   6.89800000   6.91400000   6.89800000

               Volume
0     107255.40000000
1      56376.30000000
2     126173.20000000
3      54565.60000000
4      50489.50000000
...               ...
3505  491086.30000000
3506  429911.70000000
3507  376043.70000000
3508  193925.80000000
3509    1275.90000000

[3510 rows x 6 columns], 'df_4h_imxusdt':           Open_Time        Open       Close        High         Low  \
0     1641801600000  3.75100000  3.73200000  4.30000000  3.71300000
1     1641816000000  3.72900000  3.59700000  3.79900000  3.41900000
2     1641830400000  3.60100000  3.65900000  3.74000000  3.54800000
3     1641844800000  3.65600000  3.78400000  3.89200000  3.64000000
4     1641859200000  3.79100000  3.59100000  3.91000000  3.52500000
...             ...         ...         ...         ...         ...
3085  1686225600000  0.72200000  0.71700000  0.72900000  0.71300000
3086  1686240000000  0.71800000  0.72000000  0.72400000  0.70900000
3087  1686254400000  0.71900000  0.71600000  0.72600000  0.71600000
3088  1686268800000  0.71600000  0.72500000  0.73600000  0.71400000
3089  1686283200000  0.72500000  0.72400000  0.72500000  0.72400000

                Volume
0     1244180.70000000
1      621287.58000000
2      315012.23000000
3      375442.29000000
4      530030.47000000
...                ...
3085   889742.29000000
3086   604539.13000000
3087   379864.54000000
3088   959164.75000000
3089     4799.64000000

[3090 rows x 6 columns], 'df_4h_roseusdt':           Open_Time        Open       Close        High         Low  \
0     1635753600000  0.18320000  0.18519000  0.18719000  0.18250000
1     1635768000000  0.18496000  0.18613000  0.18725000  0.18379000
2     1635782400000  0.18613000  0.18514000  0.18675000  0.18271000
3     1635796800000  0.18496000  0.18429000  0.18600000  0.18267000
4     1635811200000  0.18429000  0.18590000  0.18630000  0.18292000
...             ...         ...         ...         ...         ...
3505  1686225600000  0.04999000  0.05065000  0.05125000  0.04997000
3506  1686240000000  0.05064000  0.05042000  0.05070000  0.04965000
3507  1686254400000  0.05041000  0.04992000  0.05047000  0.04982000
3508  1686268800000  0.04998000  0.05019000  0.05049000  0.04962000
3509  1686283200000  0.05018000  0.05025000  0.05025000  0.05018000

                 Volume
0      8630660.70000000
1      9982127.40000000
2     10758219.30000000
3     10783187.40000000
4      4513259.30000000
...                 ...
3505  24404893.30000000
3506  15531107.00000000
3507   8090144.00000000
3508   5817018.50000000
3509     22574.90000000

[3510 rows x 6 columns], 'df_4h_linausdt':           Open_Time        Open       Close        High         Low  \
0     1635753600000  0.05218000  0.05138000  0.05391000  0.05102000
1     1635768000000  0.05141000  0.05297000  0.05374000  0.05141000
2     1635782400000  0.05298000  0.05263000  0.05310000  0.05119000
3     1635796800000  0.05261000  0.05282000  0.05315000  0.05184000
4     1635811200000  0.05281000  0.05380000  0.05397000  0.05204000
...             ...         ...         ...         ...         ...
3505  1686225600000  0.01235700  0.01229200  0.01270000  0.01214300
3506  1686240000000  0.01229000  0.01249800  0.01257600  0.01183700
3507  1686254400000  0.01249800  0.01242500  0.01272600  0.01242500
3508  1686268800000  0.01242500  0.01245900  0.01268100  0.01230400
3509  1686283200000  0.01245900  0.01250100  0.01250100  0.01244700

                  Volume
0      74404339.27000000
1      64446213.81000000
2      45430058.44000000
3      21503646.50000000
4      39634616.60000000
...                  ...
3505  336223119.14000000
3506  386069073.45000000
3507  196764292.90000000
3508  239055765.41000000
3509    2196394.74000000

[3510 rows x 6 columns], 'df_4h_ftmusdt':           Open_Time        Open       Close        High         Low  \
0     1635753600000  2.86640000  2.78770000  2.89540000  2.77210000
1     1635768000000  2.78820000  2.74360000  2.81720000  2.72950000
2     1635782400000  2.74450000  2.71950000  2.74520000  2.67080000
3     1635796800000  2.72010000  2.70150000  2.72140000  2.66880000
4     1635811200000  2.70290000  2.68930000  2.76200000  2.67560000
...             ...         ...         ...         ...         ...
3505  1686225600000  0.29320000  0.29690000  0.30110000  0.29240000
3506  1686240000000  0.29690000  0.29660000  0.29790000  0.29300000
3507  1686254400000  0.29660000  0.29590000  0.29850000  0.29540000
3508  1686268800000  0.29580000  0.29320000  0.29750000  0.29020000
3509  1686283200000  0.29330000  0.29300000  0.29330000  0.29290000

                 Volume
0     13164680.00000000
1     12748022.00000000
2     13373213.00000000
3      9282695.00000000
4     13124164.00000000
...                 ...
3505  23656682.00000000
3506   9366390.00000000
3507   6382030.00000000
3508  12167641.00000000
3509     62149.00000000

[3510 rows x 6 columns], 'df_4h_adausdt':           Open_Time        Open       Close        High         Low  \
0     1635753600000  1.97800000  1.97400000  2.01900000  1.97100000
1     1635768000000  1.97500000  1.96800000  1.98500000  1.95500000
2     1635782400000  1.96800000  1.95100000  1.97100000  1.93300000
3     1635796800000  1.95200000  1.94900000  1.95400000  1.93100000
4     1635811200000  1.94900000  1.94700000  1.95400000  1.93300000
...             ...         ...         ...         ...         ...
3505  1686225600000  0.32670000  0.32880000  0.33080000  0.32600000
3506  1686240000000  0.32880000  0.32320000  0.32880000  0.31980000
3507  1686254400000  0.32330000  0.32280000  0.32580000  0.32230000
3508  1686268800000  0.32290000  0.32050000  0.32370000  0.31750000
3509  1686283200000  0.32050000  0.31990000  0.32060000  0.31980000

                 Volume
0     36117725.90000000
1     23211990.70000000
2     20023740.50000000
3     16095164.10000000
4     14993686.20000000
...                 ...
3505  25180336.00000000
3506  21236113.60000000
3507   8418042.40000000

In [9]:
def get_klines(symbol, interval):
    global dataframes
    df = dataframes[f'df_{interval}_{symbol}']
    df = df[['Open_Time', 'Open', 'Close', "High", "Low", 'Volume']].astype(float)
    df = df.set_index('Open_Time')

    df.index = pd.to_datetime(df.index, unit='ms') + pd.Timedelta(hours=timezone)
    df = df[~df.index.duplicated(keep='first')]

    return df

In [10]:
symbol_dfs = {}
def multi_timeframes(symbol):
    df = get_klines(symbol, interval_arr[0]).copy() # eth 1h
    df = df.astype(float).round(4)

    for interval in interval_arr:
        raw_df = get_klines(symbol, interval)
        # ema
        for ema in ema_arr:
            column_name = f'ema_{ema}_{interval}' # eth 1h 4th ema
            df[column_name] = ta.trend.EMAIndicator(raw_df.Close, window=ema, fillna=True).ema_indicator()

        # rsi
    #     rsi = ta.momentum.RSIIndicator(raw_df.Close, window = rsi_int)
    #     df[f'rsi_{interval}'] = rsi.rsi()

        # atr
    #         df['atr'] = ta.volatility.average_true_range(df.High, df.Low, df.Close)


    # reset index and set current index as a column
    df = df.reset_index()

    # set new index with integers
    df = df.set_index(pd.RangeIndex(len(df)))

    # time_format(timezone)
    df['Open_Time'] = df['Open_Time'].dt.strftime('%Y-%m-%d %H:%M:%S')

    # fill up higher time frame empty values with equal interval between each value
    df = df.replace('', np.nan)
    df['ema_8_4h'] = df['ema_8_4h'].interpolate()
    df['ema_18_4h'] = df['ema_18_4h'].interpolate()
    df['ema_38_4h'] = df['ema_38_4h'].interpolate()
    symbol_dfs[f'df_{symbol}'] = df
    return symbol_dfs[f'df_{symbol}']

In [11]:
multi_timeframes(symbol_arr[1])
print(symbol_dfs)

{'df_crvusdt':                  Open_Time   Open  Close   High    Low    Volume  ema_8_1h  \
0      2021-11-01 14:00:00  4.301  4.326  4.353  4.270  303124.4  4.326000
1      2021-11-01 15:00:00  4.327  4.394  4.417  4.327  601910.4  4.341111
2      2021-11-01 16:00:00  4.395  4.376  4.436  4.347  380985.9  4.348864
3      2021-11-01 17:00:00  4.376  4.366  4.405  4.362  422365.0  4.352672
4      2021-11-01 18:00:00  4.365  4.404  4.461  4.365  651086.5  4.364078
...                    ...    ...    ...    ...    ...       ...       ...
14033  2023-06-09 08:00:00  0.761  0.757  0.761  0.757  131880.0  0.760679
14034  2023-06-09 09:00:00  0.757  0.759  0.762  0.757   95627.5  0.760306
14035  2023-06-09 10:00:00  0.759  0.755  0.760  0.751  437625.1  0.759127
14036  2023-06-09 11:00:00  0.755  0.758  0.759  0.752  152087.0  0.758876
14037  2023-06-09 12:00:00  0.759  0.758  0.759  0.758     224.9  0.758682

       ema_18_1h  ema_38_1h  ema_8_4h  ema_18_4h  ema_38_4h
0       4.326000   4.326000       NaN        NaN        NaN
1       4.333158   4.329487       NaN        NaN        NaN
2       4.337668   4.331872  4.452000   4.452000   4.452000
3       4.340650   4.333623  4.453778   4.452842   4.452410
4       4.347318   4.337232  4.455556   4.453684   4.452821
...          ...        ...       ...        ...        ...
14033   0.760854   0.764255  0.762118   0.773052   0.792571
14034   0.760659   0.763985  0.761889   0.772655   0.792128
14035   0.760064   0.763525  0.761661   0.772259   0.791684
14036   0.759846   0.763241  0.761432   0.771863   0.791241
14037   0.759652   0.762973  0.761203   0.771467   0.790798

[14038 rows x 12 columns]}

In [12]:
# def check_cross(df, kd_dir):
#     up = df['slow_k'] > df['slow_d']
#     down = df['slow_k'] < df['slow_d']
#     if kd_dir == 'Up':
#         return up.diff() & up
#     if kd_dir == 'Any':
#         return up.diff()
#     if kd_dir == 'Down':
#         return down.diff() & down


def indicators(df):

# ema
#     for i in (200, 500, 1000):
#         df['ema_'+str(i)] = ta.trend.ema_indicator(df.Close, window=i)

# atr
#     df['atr'] = ta.volatility.average_true_range(df.High, df.Low, df.Close)
    
# rsi
#     rsi_int = 14
#     df['rsi'] = ta.momentum.RSIIndicator(df['Close'], window = rsi_int).rsi()

# bband
    bb_int = 30
    bb_dev = 2
    bb = ta.volatility.BollingerBands(df['Close'], window=bb_int, window_dev=bb_dev)
    df['bb_u'] = bb.bollinger_hband()
    df['bb_m'] = bb.bollinger_mavg()
    df['bb_l'] = bb.bollinger_lband()

# kd
#     df['slow_k']= ta.momentum.stoch(df['High'], df['Low'], df['Close'], 17, 5)
#     df['slow_d'] = ta.momentum.stoch_signal(df['High'], df['Low'], df['Close'], 17, 5)
    
# kd cross
#     df['kd_cross'] = check_cross(df, kd_dir)

In [13]:
def conditions(df, ep_per):
    df['c1'] = df['ema_8_1h'] <= df['ema_18_1h']
    df['c2'] = df['ema_18_1h'] <= df['ema_38_1h']
    df['c3'] = df['ema_8_4h'] <= df['ema_38_4h']
    
    # signal
    df['signal'] = df['c1'] & df['c2'] & df['c3']
    
    # open_entry
    df['open_entry'] = df['signal'] & (df['High'] >= df['ema_18_4h'] * ep_per)
    
    return df

In [14]:
def entries(df, ep_per, sl_per, sl_det):

    in_position = False
    stop_loss = np.nan
    take_profit = np.nan
    close_val = df['Close']
    open_val = df['Open']
    high_val = df['High']
    ema_18_val = df['ema_18_4h']
    vol_val = df['Volume']

    df['position'] = ''  # Create an empty column for position
    df['take_profit'] = np.nan

    for index, row in df.iterrows():

        if index == 0:
            continue

        elif row['open_entry']:
            df.at[index, 'entry_p'] = ema_18_val.at[index] * ep_per
            df.at[index, 'stop_loss'] = high_val.at[index] * sl_per
            df.at[index, 'take_profit'] = ema_18_val.at[index] * ep_per * 0.9
            df.at[index, 'position'] = 'Short'
            in_position = True
            stop_loss = df.at[index, 'stop_loss']
            take_profit = df.at[index, 'take_profit']

        elif in_position and row[sl_det] >= stop_loss:
            df.at[index, 'position'] = 'Stop'
            in_position = False
            stop_loss = np.nan
            take_profit = np.nan

        # set take profit
        elif in_position and row['Low'] <= row['bb_l']:
            df.at[index, 'position'] = 'Buy'
            in_position = False
            stop_loss = np.nan
            take_profit = np.nan

        elif in_position and (((vol_val.at[index] > vol_val.shift(1).at[index]) &
                              (open_val.shift(1).at[index] > close_val.shift(1).at[index]) &
                              (open_val.at[index] < close_val.at[index]) & 
                              (high_val.at[index] > open_val.shift(1).at[index])) or
                              (high_val.at[index] >= stop_loss)):
            df.at[index, 'position'] = 'Buy'
            in_position = False
            stop_loss = np.nan
            take_profit = np.nan  
            
    df = df[(df['open_entry']) | (df['position'] != '')]

In [15]:
# 部位回測
def backtest(df, symbol, sl_det):

    df = df.reset_index(drop = True)
    df = df[(df['position'] == 'Short') |
                  (df['position'] == 'Buy') |
                  (df['position'] == 'Stop')]

    # 一次進場多少單位
    pos_size = 200

    col = ['Open_Time', 'Open', 'Close', 'High', 'Low', 'position','entry_p', 'stop_loss', 'take_profit']
    pos = df[col]
    pos = pos.reset_index(drop = True)


    for index, row in pos.iterrows():

        current_pos = 0

        # 進場
        if pos.at[index, 'position'] == 'Short':
            pos.at[index, 'size'] = pos_size / pos.at[index, 'entry_p']
            pos.exit_p = np.nan

        # 出場
        if pos.at[index, 'position'] == 'Buy' or pos.at[index, 'position'] == 'Stop':

            # 停利：達成條件時收盤價
            if pos.at[index, 'position'] == 'Buy':
                pos.at[index, 'exit_p'] = pos.at[index, 'Close']
                
#                 for i in range(index -1, -1, -1):
#                     if pos.at[i, 'position'] == 'Buy':
#                         pos.at[index, 'exit_p'] = pos.at[i, 'take_profit']
#                     break

            # 停損：打到進場停損點（往回跌代，直到最近的'Buy'及其'stop_loss'）
            if (pos.at[index, 'position'] == 'Stop') & (sl_det == 'Close'):
                pos.at[index, 'exit_p'] = pos.at[index, 'Close']
                
            if (pos.at[index, 'position'] == 'Stop') & (sl_det == 'High'):
                for i in range(index -1, -1, -1):
                    if pos.at[i, 'position'] == 'Short':
                        pos.at[index, 'exit_p'] = pos.at[i, 'stop_loss']
                    break

            # 計算每次出場部位大小（每次出場皆清倉）
            for i in range(index -1, -1, -1):
                if pos.at[i, 'position'] == 'Short':
                    current_pos += pos.at[i, 'size']
                    if i == 0:
                        pos.at[index, 'size'] = -current_pos
                    else:
                        continue
                else:
                    pos.at[index, 'size'] = -current_pos
                    current_pos = 0
                    break


    # 計算部位價值
    for index, row in pos.iterrows():
        if pos.at[index, 'position'] == 'Short':
            pos.at[index, 'amt'] = round(pos.at[index, 'size'] * pos.at[index, 'entry_p'], 4)
        elif pos.at[index, 'position'] == 'Buy' or pos.at[index, 'position'] == 'Stop':
            pos.at[index, 'amt'] = round(pos.at[index, 'size'] * pos.at[index, 'exit_p'], 4)


    # 若最後一筆為 Buy，移除該單，迭代驗證
    for index, row in pos.iloc[::-1].iterrows():
        if row['position'] == 'Short':
            pos = pos.drop(index)
        else:
            break


    # 手續費、滑點、價差
    fee = 0.05 / 100
    amt_abs_sum = pos.amt.abs().sum()
    ttl_fee = amt_abs_sum * fee

    # 損益
    leverage = 10
    ttl_profit = pos.amt.sum() - ttl_fee

    
    # 計算獲利/虧損次數
    agg_amts = []

    for i in range(len(pos) - 1, -1, -1):

        if pos.loc[i, 'position'] in ['Stop', 'Buy']:

            # look out for the + sign
            total_amt = pos.loc[i, 'amt'] - np.absolute(pos.loc[i, 'amt']) * fee

            # iterate backwards from the current row until reaching another 'Stop' or 'Sell'
            # watch out for the + in total_amt += trading_fee
            j = i - 1
            while j >= 0 and pos.loc[j, 'position'] not in ['Stop', 'Buy']:
                total_amt += pos.loc[j, 'amt']
                trading_fee = np.absolute(pos.loc[j, 'amt']) * fee
                total_amt -= trading_fee
                j -= 1

            # add the aggregated amount to the list
            agg_amts.append(total_amt)

    agg_amts.reverse()

    
    # 計算進場最大部位，最大損益
    consec_entry = 0
    position_amt_sum = 0
    max_consec_entry = 0
    max_position = 0
    max_profit = 0
    max_loss = 0

    for index, row in pos.iterrows():

        if row['position'] == 'Short':

            consec_entry += 1
            position_amt_sum += row['amt']

        elif row['position'] in ['Buy', 'Stop']:

            if consec_entry > max_consec_entry:
                max_consec_entry = consec_entry
                max_position = position_amt_sum

            position_amt_sum += row['amt']

            if position_amt_sum > max_profit:
                max_profit = position_amt_sum

            if position_amt_sum < max_loss:
                max_loss = position_amt_sum

            consec_entry = 0
            position_amt_sum = 0

        else:
            pass


    # 最大部位
    profit_per = "{:.2f}%".format(ttl_profit / (max_position/leverage) * 100)


    # 勝率
    wins = 0
    loses = 0

    for trade in agg_amts:
        if trade > 0:
            wins += 1
        elif trade < 0:
            loses += 1

    win_rate = "{:.2f}%".format(wins / (wins + loses) * 100)

    cumulative_values = []
    cumulative_sum = 0

    for value in agg_amts:
        cumulative_sum += value
        cumulative_values.append(cumulative_sum)

    max_drawdown = min(cumulative_values)
    
    # 結果
    result = {'Profit': [round(ttl_profit, 2)],
              'Fee': [round(ttl_fee, 2)],
              'Max_Profit': [round(max_profit, 2)],
              'Max_Loss': [round(max_loss, 2)],
              'Max_Entry': [max_consec_entry],
              'Max_Position': [round(max_position, 2)],
              'Profit_%': [profit_per],
              'Win_Rate': [win_rate],
              'PF_Ratio': [round(ttl_profit/ttl_fee, 2)],
              'Max_Drawdown': [round(max_drawdown,2)]}


    result_df = pd.DataFrame(result)
    
#     pos.to_csv(f'{symbol}_{sl_det}.csv')

    return result_df, ttl_profit, win_rate, ttl_fee

In [16]:
# iterate using start_time, under same time interval, test different variables
def run_backtest():
    
    results_df = pd.DataFrame()
    
    symbol_list = []
    sl_per_list = []
    ep_per_list = []
    sl_det_list = []

    i = 0

    loop_start_time = time.time()
    
    parameters = [(symbol, sl_per, ep_per, sl_det) 
                  for symbol in symbol_arr
                  for sl_per in sl_per_arr
                  for ep_per in ep_per_arr
                  for sl_det in sl_det_arr]
    
    for symbol, sl_per, ep_per, sl_det in parameters:

        df = multi_timeframes(symbol)
        df = df.reset_index()
        indicators(df)
        conditions(df, ep_per)
        entries(df, ep_per, sl_per, sl_det)
        backtest_df, ttl_profit, win_rate, fee = backtest(df, symbol, sl_det)

        results_df = pd.concat([results_df, backtest_df], ignore_index = True)

        symbol_list.append(symbol)
        sl_per_list.append(sl_per)
        ep_per_list.append(ep_per)
        sl_det_list.append(sl_det)

        i += 1
        
        print(f" {i} - {symbol}, sl: {sl_per}, tp: {ep_per}, {sl_det}, {round(ttl_profit, 2)}, {round(fee, 2)}, {round(ttl_profit/fee, 2)}, {win_rate} ")

    loop_end_time = time.time()

    print("Time taken to execute for loop:", loop_end_time - loop_start_time, "seconds")

    results_df['symbol'] = symbol_list
    results_df['sl_per'] = sl_per_list
    results_df['ep_per'] = ep_per_list
    results_df['sl_det'] = sl_det_list

    results_df = results_df[['symbol',
                             'sl_per', 'ep_per', 'sl_det',
                             'Profit', 'Fee', 'Max_Profit', 'Max_Loss',
                             'Max_Entry', 'Max_Position', 'Profit_%', 'Win_Rate', 'PF_Ratio', 'Max_Drawdown'
                            ]]
    
    return results_df

In [17]:
results_df = run_backtest()
results_df = results_df.sort_values('Profit', ascending = False)
# print(results_df)

 1 - ethusdt, sl: 0.999, tp: 1.005, Close, 214.36, 10.29, 20.84, 69.44%
 2 - ethusdt, sl: 0.999, tp: 1.005, High, 217.26, 10.29, 21.12, 66.67%
 3 - ethusdt, sl: 0.999, tp: 0.999, Close, 433.7, 47.96, 9.04, 61.54%
 4 - ethusdt, sl: 0.999, tp: 0.999, High, 472.84, 47.94, 9.86, 55.56%
 5 - ethusdt, sl: 0.999, tp: 0.995, Close, 503.81, 133.88, 3.76, 55.02%
 6 - ethusdt, sl: 0.999, tp: 0.995, High, 706.73, 133.78, 5.28, 52.63%
 7 - ethusdt, sl: 0.999, tp: 0.99, Close, 323.22, 264.31, 1.22, 50.95%
 8 - ethusdt, sl: 0.999, tp: 0.99, High, 802.01, 264.07, 3.04, 49.05%
 9 - ethusdt, sl: 1.003, tp: 1.005, Close, 213.08, 10.29, 20.71, 71.43%
 10 - ethusdt, sl: 1.003, tp: 1.005, High, 216.78, 10.29, 21.07, 71.43%
 11 - ethusdt, sl: 1.003, tp: 0.999, Close, 409.35, 47.97, 8.53, 60.53%
 12 - ethusdt, sl: 1.003, tp: 0.999, High, 423.1, 47.96, 8.82, 58.77%
 13 - ethusdt, sl: 1.003, tp: 0.995, Close, 465.88, 132.7, 3.51, 56.22%
 14 - ethusdt, sl: 1.003, tp: 0.995, High, 612.63, 132.63, 4.62, 54.73%
 15 - ethusdt, sl: 1.003, tp: 0.99, Close, 249.8, 261.74, 0.95, 51.56%
 16 - ethusdt, sl: 1.003, tp: 0.99, High, 531.82, 261.6, 2.03, 50.39%
 17 - ethusdt, sl: 1.007, tp: 1.005, Close, 212.57, 10.29, 20.66, 74.29%
 18 - ethusdt, sl: 1.007, tp: 1.005, High, 208.54, 10.29, 20.26, 74.29%
 19 - ethusdt, sl: 1.007, tp: 0.999, Close, 367.22, 47.99, 7.65, 59.65%
 20 - ethusdt, sl: 1.007, tp: 0.999, High, 374.48, 47.99, 7.8, 58.77%
 21 - ethusdt, sl: 1.007, tp: 0.995, Close, 368.99, 132.75, 2.78, 56.78%
 22 - ethusdt, sl: 1.007, tp: 0.995, High, 450.8, 132.71, 3.4, 56.28%
 23 - ethusdt, sl: 1.007, tp: 0.99, Close, 64.99, 261.84, 0.25, 52.00%
 24 - ethusdt, sl: 1.007, tp: 0.99, High, 234.8, 261.75, 0.9, 52.00%
 25 - ethusdt, sl: 1.011, tp: 1.005, Close, 209.37, 10.29, 20.35, 74.29%
 26 - ethusdt, sl: 1.011, tp: 1.005, High, 202.68, 10.29, 19.69, 74.29%
 27 - ethusdt, sl: 1.011, tp: 0.999, Close, 372.83, 47.99, 7.77, 59.65%
 28 - ethusdt, sl: 1.011, tp: 0.999, High, 362.98, 47.99, 7.56, 59.65%
 29 - ethusdt, sl: 1.011, tp: 0.995, Close, 365.7, 132.75, 2.75, 57.87%
 30 - ethusdt, sl: 1.011, tp: 0.995, High, 370.47, 132.75, 2.79, 57.87%
 31 - ethusdt, sl: 1.011, tp: 0.99, Close, -58.85, 261.9, -0.22, 52.82%
 32 - ethusdt, sl: 1.011, tp: 0.99, High, 37.76, 261.85, 0.14, 52.82%
 33 - crvusdt, sl: 0.999, tp: 1.005, Close, 255.27, 16.26, 15.7, 63.16%
 34 - crvusdt, sl: 0.999, tp: 1.005, High, 275.89, 16.25, 16.97, 52.63%
 35 - crvusdt, sl: 0.999, tp: 0.999, Close, 520.86, 43.72, 11.91, 61.16%
 36 - crvusdt, sl: 0.999, tp: 0.999, High, 558.15, 43.7, 12.77, 53.72%
 37 - crvusdt, sl: 0.999, tp: 0.995, Close, 622.74, 88.44, 7.04, 58.14%
 38 - crvusdt, sl: 0.999, tp: 0.995, High, 764.13, 88.37, 8.65, 57.56%
 39 - crvusdt, sl: 0.999, tp: 0.99, Close, 708.32, 161.37, 4.39, 56.11%
 40 - crvusdt, sl: 0.999, tp: 0.99, High, 1030.61, 161.2, 6.39, 54.75%
 41 - crvusdt, sl: 1.003, tp: 1.005, Close, 266.41, 16.26, 16.39, 63.16%
 42 - crvusdt, sl: 1.003, tp: 1.005, High, 282.14, 16.25, 17.36, 57.89%
 43 - crvusdt, sl: 1.003, tp: 0.999, Close, 515.02, 43.72, 11.78, 60.50%
 44 - crvusdt, sl: 1.003, tp: 0.999, High, 522.77, 43.72, 11.96, 57.98%
 45 - crvusdt, sl: 1.003, tp: 0.995, Close, 622.57, 88.44, 7.04, 59.76%
 46 - crvusdt, sl: 1.003, tp: 0.995, High, 679.3, 88.42, 7.68, 58.58%
 47 - crvusdt, sl: 1.003, tp: 0.99, Close, 758.45, 161.34, 4.7, 57.34%
 48 - crvusdt, sl: 1.003, tp: 0.99, High, 925.55, 161.26, 5.74, 56.88%
 49 - crvusdt, sl: 1.007, tp: 1.005, Close, 263.79, 16.26, 16.22, 64.91%
 50 - crvusdt, sl: 1.007, tp: 1.005, High, 282.57, 16.25, 17.39, 63.16%
 51 - crvusdt, sl: 1.007, tp: 0.999, Close, 536.11, 43.71, 12.27, 63.03%
 52 - crvusdt, sl: 1.007, tp: 0.999, High, 555.57, 43.7, 12.71, 61.34%
 53 - crvusdt, sl: 1.007, tp: 0.995, Close, 692.27, 88.41, 7.83, 61.90%
 54 - crvusdt, sl: 1.007, tp: 0.995, High, 737.49, 88.39, 8.34, 61.31%
 55 - crvusdt, sl: 1.007, tp: 0.99, Close, 850.61, 161.29, 5.27, 58.49%
 56 - crvusdt, sl: 1.007, tp: 0.99, High, 985.07, 161.23, 6.11, 58.49%
 57 - crvusdt, sl: 1.011, tp: 1.005, Close, 272.57, 16.26, 16.77, 66.67%
 58 - crvusdt, sl: 1.011, tp: 1.005, High, 283.17, 16.25, 17.43, 64.91%
 59 - crvusdt, sl: 1.011, tp: 0.999, Close, 545.17, 43.71, 12.47, 64.41%
 60 - crvusdt, sl: 1.011, tp: 0.999, High, 552.61, 43.7, 12.65, 63.56%
 61 - crvusdt, sl: 1.011, tp: 0.995, Close, 677.63, 88.42, 7.66, 63.47%
 62 - crvusdt, sl: 1.011, tp: 0.995, High, 699.15, 88.41, 7.91, 62.87%
 63 - crvusdt, sl: 1.011, tp: 0.99, Close, 850.32, 161.29, 5.27, 59.52%
 64 - crvusdt, sl: 1.011, tp: 0.99, High, 924.17, 161.26, 5.73, 59.52%
 65 - injusdt, sl: 0.999, tp: 1.005, Close, 607.14, 28.08, 21.62, 72.83%
 66 - injusdt, sl: 0.999, tp: 1.005, High, 598.1, 28.09, 21.29, 66.30%
 67 - injusdt, sl: 0.999, tp: 0.999, Close, 858.11, 55.94, 15.34, 65.33%
 68 - injusdt, sl: 0.999, tp: 0.999, High, 864.89, 55.94, 15.46, 60.67%
 69 - injusdt, sl: 0.999, tp: 0.995, Close, 1046.98, 98.43, 10.64, 65.58%
 70 - injusdt, sl: 0.999, tp: 0.995, High, 1202.32, 98.35, 12.22, 62.33%
 71 - injusdt, sl: 0.999, tp: 0.99, Close, 646.98, 180.19, 3.59, 63.38%
 72 - injusdt, sl: 0.999, tp: 0.99, High, 1249.6, 179.89, 6.95, 61.27%
 73 - injusdt, sl: 1.003, tp: 1.005, Close, 607.53, 28.08, 21.63, 75.00%
 74 - injusdt, sl: 1.003, tp: 1.005, High, 586.77, 28.09, 20.89, 73.91%
 75 - injusdt, sl: 1.003, tp: 0.999, Close, 845.49, 55.95, 15.11, 67.57%
 76 - injusdt, sl: 1.003, tp: 0.999, High, 825.58, 55.96, 14.75, 66.22%
 77 - injusdt, sl: 1.003, tp: 0.995, Close, 1009.68, 98.45, 10.26, 65.40%
 78 - injusdt, sl: 1.003, tp: 0.995, High, 1105.64, 98.4, 11.24, 65.40%
 79 - injusdt, sl: 1.003, tp: 0.99, Close, 620.4, 180.2, 3.44, 62.54%
 80 - injusdt, sl: 1.003, tp: 0.99, High, 1031.96, 179.99, 5.73, 62.19%
 81 - injusdt, sl: 1.007, tp: 1.005, Close, 639.23, 28.07, 22.78, 80.00%
 82 - injusdt, sl: 1.007, tp: 1.005, High, 599.89, 28.09, 21.36, 77.78%
 83 - injusdt, sl: 1.007, tp: 0.999, Close, 885.28, 55.93, 15.83, 71.53%
 84 - injusdt, sl: 1.007, tp: 0.999, High, 830.27, 55.96, 14.84, 70.14%
 85 - injusdt, sl: 1.007, tp: 0.995, Close, 1092.19, 98.4, 11.1, 67.48%
 86 - injusdt, sl: 1.007, tp: 0.995, High, 1102.04, 98.4, 11.2, 67.48%
 87 - injusdt, sl: 1.007, tp: 0.99, Close, 769.48, 180.13, 4.27, 64.36%
 88 - injusdt, sl: 1.007, tp: 0.99, High, 1031.81, 179.99, 5.73, 64.36%
 89 - injusdt, sl: 1.011, tp: 1.005, Close, 653.63, 28.06, 23.29, 79.78%
 90 - injusdt, sl: 1.011, tp: 1.005, High, 610.25, 28.08, 21.73, 78.65%
 91 - injusdt, sl: 1.011, tp: 0.999, Close, 901.88, 55.92, 16.13, 72.54%
 92 - injusdt, sl: 1.011, tp: 0.999, High, 839.95, 55.95, 15.01, 71.83%
 93 - injusdt, sl: 1.011, tp: 0.995, Close, 1099.12, 98.4, 11.17, 69.31%
 94 - injusdt, sl: 1.011, tp: 0.995, High, 1081.83, 98.41, 10.99, 69.31%
 95 - injusdt, sl: 1.011, tp: 0.99, Close, 764.22, 180.13, 4.24, 65.56%
 96 - injusdt, sl: 1.011, tp: 0.99, High, 924.52, 180.05, 5.13, 65.56%
 97 - imxusdt, sl: 0.999, tp: 1.005, Close, 323.86, 20.03, 16.17, 67.92%
 98 - imxusdt, sl: 0.999, tp: 1.005, High, 293.33, 20.04, 14.64, 60.38%
 99 - imxusdt, sl: 0.999, tp: 0.999, Close, 576.16, 48.49, 11.88, 66.04%
 100 - imxusdt, sl: 0.999, tp: 0.999, High, 584.96, 48.48, 12.07, 59.43%
 101 - imxusdt, sl: 0.999, tp: 0.995, Close, 801.61, 80.96, 9.9, 62.65%
 102 - imxusdt, sl: 0.999, tp: 0.995, High, 856.36, 80.93, 10.58, 57.23%
 103 - imxusdt, sl: 0.999, tp: 0.99, Close, 891.45, 140.68, 6.34, 57.83%
 104 - imxusdt, sl: 0.999, tp: 0.99, High, 1092.86, 140.58, 7.77, 55.22%
 105 - imxusdt, sl: 1.003, tp: 1.005, Close, 335.64, 20.02, 16.76, 66.04%
 106 - imxusdt, sl: 1.003, tp: 1.005, High, 277.12, 20.05, 13.82, 62.26%
 107 - imxusdt, sl: 1.003, tp: 0.999, Close, 564.34, 48.49, 11.64, 62.26%
 108 - imxusdt, sl: 1.003, tp: 0.999, High, 519.05, 48.52, 10.7, 58.49%
 109 - imxusdt, sl: 1.003, tp: 0.995, Close, 760.64, 80.98, 9.39, 61.11%
 110 - imxusdt, sl: 1.003, tp: 0.995, High, 735.36, 80.99, 9.08, 58.02%
 111 - imxusdt, sl: 1.003, tp: 0.99, Close, 843.63, 140.71, 6.0, 58.48%
 112 - imxusdt, sl: 1.003, tp: 0.99, High, 905.48, 140.68, 6.44, 55.80%
 113 - imxusdt, sl: 1.007, tp: 1.005, Close, 343.73, 20.02, 17.17, 67.92%

 114 - imxusdt, sl: 1.007, tp: 1.005, High, 311.32, 20.03, 15.54, 67.92%
 115 - imxusdt, sl: 1.007, tp: 0.999, Close, 547.77, 48.5, 11.29, 62.50%
 116 - imxusdt, sl: 1.007, tp: 0.999, High, 541.77, 48.5, 11.17, 62.50%
 117 - imxusdt, sl: 1.007, tp: 0.995, Close, 750.21, 80.98, 9.26, 61.01%
 118 - imxusdt, sl: 1.007, tp: 0.995, High, 750.71, 80.98, 9.27, 60.38%
 119 - imxusdt, sl: 1.007, tp: 0.99, Close, 800.67, 140.73, 5.69, 58.64%
 120 - imxusdt, sl: 1.007, tp: 0.99, High, 823.52, 140.72, 5.85, 58.18%
 121 - imxusdt, sl: 1.011, tp: 1.005, Close, 357.28, 20.01, 17.85, 69.81%
 122 - imxusdt, sl: 1.011, tp: 1.005, High, 312.25, 20.03, 15.59, 69.81%
 123 - imxusdt, sl: 1.011, tp: 0.999, Close, 530.29, 48.51, 10.93, 63.46%
 124 - imxusdt, sl: 1.011, tp: 0.999, High, 511.95, 48.52, 10.55, 63.46%
 125 - imxusdt, sl: 1.011, tp: 0.995, Close, 744.34, 80.99, 9.19, 62.82%
 126 - imxusdt, sl: 1.011, tp: 0.995, High, 722.09, 81.0, 8.91, 62.82%
 127 - imxusdt, sl: 1.011, tp: 0.99, Close, 815.03, 140.72, 5.79, 59.81%
 128 - imxusdt, sl: 1.011, tp: 0.99, High, 753.78, 140.75, 5.36, 59.81%
 129 - roseusdt, sl: 0.999, tp: 1.005, Close, 324.17, 14.83, 21.86, 76.27%
 130 - roseusdt, sl: 0.999, tp: 1.005, High, 305.08, 14.84, 20.56, 66.10%
 131 - roseusdt, sl: 0.999, tp: 0.999, Close, 659.41, 52.04, 12.67, 65.19%
 132 - roseusdt, sl: 0.999, tp: 0.999, High, 682.27, 52.03, 13.11, 58.52%
 133 - roseusdt, sl: 0.999, tp: 0.995, Close, 1024.95, 100.44, 10.2, 63.11%
 134 - roseusdt, sl: 0.999, tp: 0.995, High, 1112.47, 100.39, 11.08, 59.71%
 135 - roseusdt, sl: 0.999, tp: 0.99, Close, 1272.08, 200.86, 6.33, 60.28%
 136 - roseusdt, sl: 0.999, tp: 0.99, High, 1528.09, 200.74, 7.61, 58.19%
 137 - roseusdt, sl: 1.003, tp: 1.005, Close, 315.46, 14.83, 21.27, 72.88%
 138 - roseusdt, sl: 1.003, tp: 1.005, High, 291.84, 14.85, 19.66, 67.80%
 139 - roseusdt, sl: 1.003, tp: 0.999, Close, 662.35, 52.04, 12.73, 65.15%
 140 - roseusdt, sl: 1.003, tp: 0.999, High, 621.95, 52.06, 11.95, 60.61%
 141 - roseusdt, sl: 1.003, tp: 0.995, Close, 1034.92, 100.43, 10.3, 65.00%
 142 - roseusdt, sl: 1.003, tp: 0.995, High, 1009.82, 100.44, 10.05, 63.50%
 143 - roseusdt, sl: 1.003, tp: 0.99, Close, 1356.94, 200.82, 6.76, 62.32%
 144 - roseusdt, sl: 1.003, tp: 0.99, High, 1391.17, 200.8, 6.93, 61.96%
 145 - roseusdt, sl: 1.007, tp: 1.005, Close, 310.98, 14.84, 20.96, 72.41%
 146 - roseusdt, sl: 1.007, tp: 1.005, High, 293.73, 14.85, 19.79, 70.69%
 147 - roseusdt, sl: 1.007, tp: 0.999, Close, 673.18, 52.04, 12.94, 64.84%
 148 - roseusdt, sl: 1.007, tp: 0.999, High, 648.55, 52.05, 12.46, 64.84%
 149 - roseusdt, sl: 1.007, tp: 0.995, Close, 1022.39, 100.44, 10.18, 66.15%
 150 - roseusdt, sl: 1.007, tp: 0.995, High, 990.98, 100.45, 9.86, 65.64%
 151 - roseusdt, sl: 1.007, tp: 0.99, Close, 1395.24, 200.8, 6.95, 63.67%
 152 - roseusdt, sl: 1.007, tp: 0.99, High, 1377.09, 200.81, 6.86, 63.67%
 153 - roseusdt, sl: 1.011, tp: 1.005, Close, 313.57, 14.84, 21.14, 74.14%
 154 - roseusdt, sl: 1.011, tp: 1.005, High, 296.06, 14.84, 19.94, 72.41%
 155 - roseusdt, sl: 1.011, tp: 0.999, Close, 672.42, 52.04, 12.92, 67.19%
 156 - roseusdt, sl: 1.011, tp: 0.999, High, 610.82, 52.07, 11.73, 65.62%
 157 - roseusdt, sl: 1.011, tp: 0.995, Close, 1011.58, 100.44, 10.07, 68.04%
 158 - roseusdt, sl: 1.011, tp: 0.995, High, 921.78, 100.49, 9.17, 67.53%
 159 - roseusdt, sl: 1.011, tp: 0.99, Close, 1404.39, 200.8, 6.99, 65.02%
 160 - roseusdt, sl: 1.011, tp: 0.99, High, 1301.03, 200.85, 6.48, 65.02%
 161 - linausdt, sl: 0.999, tp: 1.005, Close, 316.17, 20.83, 15.18, 65.57%
 162 - linausdt, sl: 0.999, tp: 1.005, High, 276.35, 20.85, 13.25, 50.82%
 163 - linausdt, sl: 0.999, tp: 0.999, Close, 486.08, 40.94, 11.87, 60.22%
 164 - linausdt, sl: 0.999, tp: 0.999, High, 502.45, 40.93, 12.28, 52.69%
 165 - linausdt, sl: 0.999, tp: 0.995, Close, 630.31, 68.25, 9.24, 58.70%
 166 - linausdt, sl: 0.999, tp: 0.995, High, 724.78, 68.2, 10.63, 53.62%
 167 - linausdt, sl: 0.999, tp: 0.99, Close, 671.69, 114.41, 5.87, 55.73%
 168 - linausdt, sl: 0.999, tp: 0.99, High, 869.73, 114.31, 7.61, 52.60%
 169 - linausdt, sl: 1.003, tp: 1.005, Close, 296.82, 20.84, 14.24, 57.89%
 170 - linausdt, sl: 1.003, tp: 1.005, High, 319.51, 20.83, 15.34, 52.63%
 171 - linausdt, sl: 1.003, tp: 0.999, Close, 468.5, 40.95, 11.44, 59.55%
 172 - linausdt, sl: 1.003, tp: 0.999, High, 481.82, 40.94, 11.77, 55.06%
 173 - linausdt, sl: 1.003, tp: 0.995, Close, 576.18, 68.28, 8.44, 58.33%
 174 - linausdt, sl: 1.003, tp: 0.995, High, 660.05, 68.24, 9.67, 56.82%
 175 - linausdt, sl: 1.003, tp: 0.99, Close, 689.36, 114.4, 6.03, 56.45%
 176 - linausdt, sl: 1.003, tp: 0.99, High, 880.27, 114.3, 7.7, 55.38%
 177 - linausdt, sl: 1.007, tp: 1.005, Close, 302.73, 20.84, 14.53, 58.93%
 178 - linausdt, sl: 1.007, tp: 1.005, High, 304.57, 20.84, 14.62, 55.36%
 179 - linausdt, sl: 1.007, tp: 0.999, Close, 478.53, 40.94, 11.69, 59.09%
 180 - linausdt, sl: 1.007, tp: 0.999, High, 445.67, 40.96, 10.88, 55.68%
 181 - linausdt, sl: 1.007, tp: 0.995, Close, 583.18, 68.27, 8.54, 58.78%
 182 - linausdt, sl: 1.007, tp: 0.995, High, 577.73, 68.28, 8.46, 57.25%
 183 - linausdt, sl: 1.007, tp: 0.99, Close, 696.33, 114.39, 6.09, 56.76%
 184 - linausdt, sl: 1.007, tp: 0.99, High, 720.72, 114.38, 6.3, 55.68%
 185 - linausdt, sl: 1.011, tp: 1.005, Close, 361.75, 20.81, 17.38, 62.50%
 186 - linausdt, sl: 1.011, tp: 1.005, High, 346.41, 20.82, 16.64, 60.71%
 187 - linausdt, sl: 1.011, tp: 0.999, Close, 585.39, 40.89, 14.32, 62.35%
 188 - linausdt, sl: 1.011, tp: 0.999, High, 539.09, 40.91, 13.18, 61.18%
 189 - linausdt, sl: 1.011, tp: 0.995, Close, 721.93, 68.2, 10.58, 62.20%
 190 - linausdt, sl: 1.011, tp: 0.995, High, 670.44, 68.23, 9.83, 61.42%
 191 - linausdt, sl: 1.011, tp: 0.99, Close, 827.14, 114.33, 7.23, 59.67%
 192 - linausdt, sl: 1.011, tp: 0.99, High, 760.32, 114.36, 6.65, 59.12%
 193 - ftmusdt, sl: 0.999, tp: 1.005, Close, 364.6, 15.21, 23.97, 61.22%
 194 - ftmusdt, sl: 0.999, tp: 1.005, High, 374.59, 15.21, 24.64, 55.10%
 195 - ftmusdt, sl: 0.999, tp: 0.999, Close, 737.89, 51.01, 14.47, 69.47%
 196 - ftmusdt, sl: 0.999, tp: 0.999, High, 788.02, 50.98, 15.46, 59.54%
 197 - ftmusdt, sl: 0.999, tp: 0.995, Close, 1011.96, 102.64, 9.86, 62.50%
 198 - ftmusdt, sl: 0.999, tp: 0.995, High, 1145.89, 102.58, 11.17, 58.15%
 199 - ftmusdt, sl: 0.999, tp: 0.99, Close, 1074.38, 184.57, 5.82, 60.98%
 200 - ftmusdt, sl: 0.999, tp: 0.99, High, 1356.56, 184.43, 7.36, 56.50%
 201 - ftmusdt, sl: 1.003, tp: 1.005, Close, 365.41, 15.21, 24.02, 61.22%
 202 - ftmusdt, sl: 1.003, tp: 1.005, High, 361.73, 15.21, 23.78, 59.18%
 203 - ftmusdt, sl: 1.003, tp: 0.999, Close, 716.11, 51.02, 14.04, 67.72%
 204 - ftmusdt, sl: 1.003, tp: 0.999, High, 738.74, 51.01, 14.48, 63.78%
 205 - ftmusdt, sl: 1.003, tp: 0.995, Close, 1004.0, 102.65, 9.78, 62.22%
 206 - ftmusdt, sl: 1.003, tp: 0.995, High, 1068.84, 102.61, 10.42, 59.44%
 207 - ftmusdt, sl: 1.003, tp: 0.99, Close, 1103.75, 184.56, 5.98, 60.50%
 208 - ftmusdt, sl: 1.003, tp: 0.99, High, 1234.74, 184.49, 6.69, 59.66%
 209 - ftmusdt, sl: 1.007, tp: 1.005, Close, 349.45, 15.22, 22.96, 63.27%
 210 - ftmusdt, sl: 1.007, tp: 1.005, High, 351.13, 15.22, 23.08, 63.27%
 211 - ftmusdt, sl: 1.007, tp: 0.999, Close, 680.58, 51.03, 13.34, 66.40%
 212 - ftmusdt, sl: 1.007, tp: 0.999, High, 688.58, 51.03, 13.49, 65.60%
 213 - ftmusdt, sl: 1.007, tp: 0.995, Close, 945.73, 102.68, 9.21, 62.01%
 214 - ftmusdt, sl: 1.007, tp: 0.995, High, 981.13, 102.66, 9.56, 60.89%
 215 - ftmusdt, sl: 1.007, tp: 0.99, Close, 949.97, 184.63, 5.15, 60.59%
 216 - ftmusdt, sl: 1.007, tp: 0.99, High, 1055.0, 184.58, 5.72, 60.17%
 217 - ftmusdt, sl: 1.011, tp: 1.005, Close, 344.03, 15.22, 22.6, 64.58%
 218 - ftmusdt, sl: 1.011, tp: 1.005, High, 342.23, 15.22, 22.48, 64.58%
 219 - ftmusdt, sl: 1.011, tp: 0.999, Close, 687.81, 51.03, 13.48, 67.48%
 220 - ftmusdt, sl: 1.011, tp: 0.999, High, 644.04, 51.05, 12.62, 66.67%
 221 - ftmusdt, sl: 1.011, tp: 0.995, Close, 940.67, 102.68, 9.16, 62.86%
 222 - ftmusdt, sl: 1.011, tp: 0.995, High, 903.36, 102.7, 8.8, 62.29%
 223 - ftmusdt, sl: 1.011, tp: 0.99, Close, 947.11, 184.63, 5.13, 61.64%

 224 - ftmusdt, sl: 1.011, tp: 0.99, High, 929.77, 184.64, 5.04, 61.64%
 225 - adausdt, sl: 0.999, tp: 1.005, Close, 196.8, 14.09, 13.96, 67.39%
 226 - adausdt, sl: 0.999, tp: 1.005, High, 192.44, 14.1, 13.65, 50.00%
 227 - adausdt, sl: 0.999, tp: 0.999, Close, 518.62, 55.71, 9.31, 62.50%
 228 - adausdt, sl: 0.999, tp: 0.999, High, 551.04, 55.7, 9.89, 53.12%
 229 - adausdt, sl: 0.999, tp: 0.995, Close, 949.41, 131.26, 7.23, 61.47%
 230 - adausdt, sl: 0.999, tp: 0.995, High, 1016.66, 131.23, 7.75, 52.75%
 231 - adausdt, sl: 0.999, tp: 0.99, Close, 972.36, 263.18, 3.69, 57.73%
 232 - adausdt, sl: 0.999, tp: 0.99, High, 1215.5, 263.06, 4.62, 54.89%
 233 - adausdt, sl: 1.003, tp: 1.005, Close, 196.12, 14.09, 13.91, 63.64%
 234 - adausdt, sl: 1.003, tp: 1.005, High, 189.82, 14.1, 13.46, 56.82%
 235 - adausdt, sl: 1.003, tp: 0.999, Close, 489.79, 55.73, 8.79, 61.90%
 236 - adausdt, sl: 1.003, tp: 0.999, High, 508.11, 55.72, 9.12, 59.52%
 237 - adausdt, sl: 1.003, tp: 0.995, Close, 861.05, 131.3, 6.56, 61.54%
 238 - adausdt, sl: 1.003, tp: 0.995, High, 895.83, 131.29, 6.82, 58.65%
 239 - adausdt, sl: 1.003, tp: 0.99, Close, 803.95, 263.27, 3.05, 58.80%
 240 - adausdt, sl: 1.003, tp: 0.99, High, 921.11, 263.21, 3.5, 58.14%
 241 - adausdt, sl: 1.007, tp: 1.005, Close, 213.93, 14.09, 15.19, 67.44%
 242 - adausdt, sl: 1.007, tp: 1.005, High, 208.96, 14.09, 14.83, 62.79%
 243 - adausdt, sl: 1.007, tp: 0.999, Close, 599.74, 55.67, 10.77, 65.57%
 244 - adausdt, sl: 1.007, tp: 0.999, High, 631.19, 55.66, 11.34, 63.93%
 245 - adausdt, sl: 1.007, tp: 0.995, Close, 965.63, 131.25, 7.36, 64.00%
 246 - adausdt, sl: 1.007, tp: 0.995, High, 1034.86, 131.22, 7.89, 63.50%
 247 - adausdt, sl: 1.007, tp: 0.99, Close, 991.17, 263.17, 3.77, 62.02%
 248 - adausdt, sl: 1.007, tp: 0.99, High, 1050.31, 263.14, 3.99, 61.67%
 249 - adausdt, sl: 1.011, tp: 1.005, Close, 215.18, 14.09, 15.28, 67.44%
 250 - adausdt, sl: 1.011, tp: 1.005, High, 216.7, 14.08, 15.39, 67.44%
 251 - adausdt, sl: 1.011, tp: 0.999, Close, 606.24, 55.67, 10.89, 66.12%
 252 - adausdt, sl: 1.011, tp: 0.999, High, 623.93, 55.66, 11.21, 66.12%
 253 - adausdt, sl: 1.011, tp: 0.995, Close, 964.28, 131.25, 7.35, 64.97%
 254 - adausdt, sl: 1.011, tp: 0.995, High, 999.75, 131.23, 7.62, 64.97%
 255 - adausdt, sl: 1.011, tp: 0.99, Close, 872.48, 263.23, 3.31, 63.60%
 256 - adausdt, sl: 1.011, tp: 0.99, High, 957.48, 263.19, 3.64, 63.25%
 257 - avaxusdt, sl: 0.999, tp: 1.005, Close, 190.01, 10.9, 17.43, 80.56%
 258 - avaxusdt, sl: 0.999, tp: 1.005, High, 184.05, 10.9, 16.88, 55.56%
 259 - avaxusdt, sl: 0.999, tp: 0.999, Close, 398.38, 39.98, 9.96, 67.96%
 260 - avaxusdt, sl: 0.999, tp: 0.999, High, 419.28, 39.97, 10.49, 60.19%
 261 - avaxusdt, sl: 0.999, tp: 0.995, Close, 673.86, 90.82, 7.42, 62.84%
 262 - avaxusdt, sl: 0.999, tp: 0.995, High, 740.53, 90.78, 8.16, 59.56%
 263 - avaxusdt, sl: 0.999, tp: 0.99, Close, 1074.58, 207.96, 5.17, 58.69%
 264 - avaxusdt, sl: 0.999, tp: 0.99, High, 1215.43, 207.89, 5.85, 54.83%
 265 - avaxusdt, sl: 1.003, tp: 1.005, Close, 193.21, 10.9, 17.73, 75.00%
 266 - avaxusdt, sl: 1.003, tp: 1.005, High, 196.35, 10.9, 18.02, 69.44%
 267 - avaxusdt, sl: 1.003, tp: 0.999, Close, 415.91, 39.97, 10.4, 67.00%
 268 - avaxusdt, sl: 1.003, tp: 0.999, High, 419.92, 39.97, 10.51, 64.00%
 269 - avaxusdt, sl: 1.003, tp: 0.995, Close, 741.12, 90.78, 8.16, 63.43%
 270 - avaxusdt, sl: 1.003, tp: 0.995, High, 773.92, 90.77, 8.53, 62.29%
 271 - avaxusdt, sl: 1.003, tp: 0.99, Close, 1088.91, 207.95, 5.24, 59.44%
 272 - avaxusdt, sl: 1.003, tp: 0.99, High, 1167.53, 207.91, 5.62, 58.63%
 273 - avaxusdt, sl: 1.007, tp: 1.005, Close, 197.26, 10.9, 18.1, 77.78%
 274 - avaxusdt, sl: 1.007, tp: 1.005, High, 197.11, 10.9, 18.09, 77.78%
 275 - avaxusdt, sl: 1.007, tp: 0.999, Close, 406.38, 39.98, 10.17, 72.73%
 276 - avaxusdt, sl: 1.007, tp: 0.999, High, 398.36, 39.98, 9.96, 71.72%
 277 - avaxusdt, sl: 1.007, tp: 0.995, Close, 709.78, 90.8, 7.82, 65.29%
 278 - avaxusdt, sl: 1.007, tp: 0.995, High, 723.56, 90.79, 7.97, 65.29%
 279 - avaxusdt, sl: 1.007, tp: 0.99, Close, 1033.12, 207.98, 4.97, 61.98%
 280 - avaxusdt, sl: 1.007, tp: 0.99, High, 1121.11, 207.94, 5.39, 61.16%
 281 - avaxusdt, sl: 1.011, tp: 1.005, Close, 204.08, 10.89, 18.74, 80.56%
 282 - avaxusdt, sl: 1.011, tp: 1.005, High, 201.51, 10.89, 18.5, 80.56%
 283 - avaxusdt, sl: 1.011, tp: 0.999, Close, 436.71, 39.96, 10.93, 74.75%
 284 - avaxusdt, sl: 1.011, tp: 0.999, High, 425.21, 39.97, 10.64, 74.75%
 285 - avaxusdt, sl: 1.011, tp: 0.995, Close, 780.76, 90.76, 8.6, 68.26%
 286 - avaxusdt, sl: 1.011, tp: 0.995, High, 756.75, 90.78, 8.34, 67.66%
 287 - avaxusdt, sl: 1.011, tp: 0.99, Close, 1190.64, 207.9, 5.73, 63.71%
 288 - avaxusdt, sl: 1.011, tp: 0.99, High, 1156.77, 207.92, 5.56, 62.87%
Time taken to execute for loop: 313.53173828125 seconds

In [19]:
results_df.to_csv(f'results_df_025.csv')