In [1]:
# start time - 1609459200000, 1641028611000, 1672564611000, 1654045261000, 1651366861000 (2021, 2022, 2023)

In [2]:
# ! conda install -c conda-forge ta --yes

In [3]:
import requests
import pandas as pd
import ta
import datetime as dt
import numpy as np
import time
import itertools
import os

In [4]:
from binance.client import Client
from dotenv import load_dotenv

# Get the path to the current directory
current_directory = os.getcwd()

# Specify the path to the .env file relative to the current directory
dotenv_path = os.path.join(current_directory, '.env')

# Load the environment variables from the .env file
load_dotenv(dotenv_path)

api_key = os.getenv('API_KEY')
api_secret = os.getenv('SECRET_KEY')

client = Client(api_key, api_secret, testnet = False)

In [5]:
interval_arr = ['1h', '4h']
ema_arr = [8, 18, 38]

ep_per_arr = [0.999, 1.001, 1.003, 1.01]

sl_per_arr = [0.998, 0.995, 0.990]

# stop loss determine candlestick
sl_det_arr = ['Close', 'Low']

In [6]:
timezone = 8
# symbol = 'ethusdt'
symbol_arr = ['ethusdt', 'crvusdt', 'xecusdt', 'injusdt', 'imxusdt', 'roseusdt', 'linausdt', 'epxusdt', 'shibusdt']

start_time = 1635743450000
end_time = round(time.time() * 1000)

def set_time():
    global start_time, end_time
    start_time = 1635743450000
    end_time = round(time.time() * 1000)

# step between timestamps in milliseconds
step = 1000

In [7]:
dataframes = {}
def create_raw(symbol_arr, interval_arr, step):
    global start_time, end_time
    
    for interval in interval_arr:
        for symbol in symbol_arr:
            set_time()
            # Fetch the data using batch requests
            data = []
            while start_time < end_time:
                limit = min(step, end_time - start_time + 1)  # Adjust the limit for the last batch
                response = client.get_klines(symbol=symbol.upper(), interval=interval, limit=limit, startTime=start_time)

                if len(response) == 0:
                    break  # No more data available, exit the loop
                data.extend(response)
                start_time = response[-1][0] + 1

            # Convert the data to a DataFrame
            columns = [
                "Open_Time", "Open", "High", "Low", "Close", "Volume", "Close_Time",
                "Quote asset volume", "Number of trades", "Taker buy base asset volume",
                "Taker buy quote asset volume", "Ignore"
            ]
            raw_df = pd.DataFrame(data, columns=columns)   

            raw_df = raw_df[['Open_Time', 'Open', 'Close', "High", "Low", 'Volume']]

            dataframes[f'df_{interval}_{symbol}'] = raw_df

In [8]:
loop_start_time = time.time()
create_raw(symbol_arr, interval_arr, step)
loop_end_time = time.time()
print("Time taken to execute for loop:", loop_end_time - loop_start_time, "seconds")
print(dataframes)

Time taken to execute for loop: 23.828450679779053 seconds
{'df_1h_ethusdt':            Open_Time           Open          Close           High  \
0      1635746400000  4225.00000000  4241.99000000  4259.14000000
1      1635750000000  4241.99000000  4302.93000000  4320.00000000
2      1635753600000  4302.94000000  4311.11000000  4338.07000000
3      1635757200000  4311.11000000  4316.56000000  4344.41000000
4      1635760800000  4316.55000000  4328.94000000  4335.00000000
...              ...            ...            ...            ...
13958  1685998800000  1805.00000000  1807.02000000  1807.05000000
13959  1686002400000  1807.01000000  1807.17000000  1809.80000000
13960  1686006000000  1807.18000000  1810.50000000  1815.88000000
13961  1686009600000  1810.49000000  1810.91000000  1812.00000000
13962  1686013200000  1810.90000000  1807.75000000  1811.35000000

                 Low          Volume
0      4198.55000000  13908.93710000
1      4241.46000000  31363.21900000
2      4294.52000000  21038.55420000
3      4310.64000000  16175.35920000
4      4313.86000000  11207.71110000
...              ...             ...
13958  1793.01000000  18489.14790000
13959  1804.91000000   9058.68630000
13960  1806.55000000  16871.32030000
13961  1808.86000000   9848.85740000
13962  1807.00000000   1480.46240000

[13963 rows x 6 columns], 'df_1h_crvusdt':            Open_Time        Open       Close        High         Low  \
0      1635746400000  4.30100000  4.32600000  4.35300000  4.27000000
1      1635750000000  4.32700000  4.39400000  4.41700000  4.32700000
2      1635753600000  4.39500000  4.37600000  4.43600000  4.34700000
3      1635757200000  4.37600000  4.36600000  4.40500000  4.36200000
4      1635760800000  4.36500000  4.40400000  4.46100000  4.36500000
...              ...         ...         ...         ...         ...
13958  1685998800000  0.77800000  0.77700000  0.78000000  0.77200000
13959  1686002400000  0.77800000  0.77800000  0.77900000  0.77600000
13960  1686006000000  0.77900000  0.77400000  0.78000000  0.77300000
13961  1686009600000  0.77400000  0.77400000  0.77800000  0.77300000
13962  1686013200000  0.77400000  0.77100000  0.77500000  0.77100000

                Volume
0      303124.40000000
1      601910.40000000
2      380985.90000000
3      422365.00000000
4      651086.50000000
...                ...
13958  588191.80000000
13959  177454.70000000
13960  502343.90000000
13961  296074.40000000
13962   67671.20000000

[13963 rows x 6 columns], 'df_1h_xecusdt':            Open_Time        Open       Close        High         Low  \
0      1635746400000  0.00017710  0.00017842  0.00017859  0.00017602
1      1635750000000  0.00017842  0.00018000  0.00018467  0.00017842
2      1635753600000  0.00017999  0.00017942  0.00018115  0.00017870
3      1635757200000  0.00017946  0.00018048  0.00018097  0.00017922
4      1635760800000  0.00018048  0.00017990  0.00018048  0.00017953
...              ...         ...         ...         ...         ...
13958  1685998800000  0.00002289  0.00002292  0.00002295  0.00002272
13959  1686002400000  0.00002292  0.00002282  0.00002295  0.00002276
13960  1686006000000  0.00002282  0.00002283  0.00002292  0.00002280
13961  1686009600000  0.00002282  0.00002285  0.00002293  0.00002279
13962  1686013200000  0.00002285  0.00002278  0.00002285  0.00002278

              Volume
0      3550731972.00
1      6418269565.00
2      4346487087.00
3      5078397918.00
4      3330584708.00
...              ...
13958  1128530448.00
13959   883614840.00
13960   517536966.00
13961   721535434.00
13962   128797018.00

[13963 rows x 6 columns], 'df_1h_injusdt':            Open_Time         Open        Close         High          Low  \
0      1635746400000  10.71800000  10.71400000  10.73400000  10.67000000
1      1635750000000  10.71500000  10.87600000  10.87600000  10.71500000
2      1635753600000  10.87600000  10.92200000  10.94000000  10.86400000
3      1635757200000  10.93100000  11.02400000  11.35000000  10.92600000
4      1635760800000  11.01000000  11.07900000  11.10700000  11.00100000
...              ...          ...          ...          ...          ...
13958  1685998800000   7.20800000   7.17500000   7.21400000   7.10000000
13959  1686002400000   7.17300000   7.13500000   7.18500000   7.08100000
13960  1686006000000   7.13700000   7.08200000   7.18900000   7.08000000
13961  1686009600000   7.08100000   7.06100000   7.10100000   7.02600000
13962  1686013200000   7.06100000   6.99900000   7.06100000   6.99200000

                Volume
0        7908.40000000
1       14399.30000000
2       14244.90000000
3       66909.20000000
4       12787.60000000
...                ...
13958   87720.10000000
13959  121989.50000000
13960   44197.80000000
13961   71624.50000000
13962   25188.10000000

[13963 rows x 6 columns], 'df_1h_imxusdt':            Open_Time        Open       Close        High         Low  \
0      1641808800000  3.75100000  3.84500000  4.30000000  3.75100000
1      1641812400000  3.84500000  3.73200000  3.88300000  3.71300000
2      1641816000000  3.72900000  3.61100000  3.79900000  3.58400000
3      1641819600000  3.61000000  3.57200000  3.64600000  3.55300000
4      1641823200000  3.57200000  3.57800000  3.66400000  3.41900000
...              ...         ...         ...         ...         ...
12274  1685998800000  0.72700000  0.72200000  0.72700000  0.71300000
12275  1686002400000  0.72200000  0.72800000  0.73000000  0.72100000
12276  1686006000000  0.72800000  0.73100000  0.73500000  0.72800000
12277  1686009600000  0.73100000  0.72300000  0.73400000  0.72100000
12278  1686013200000  0.72400000  0.71800000  0.72400000  0.71600000

                 Volume
0      1020857.48000000
1       223323.22000000
2       135615.70000000
3        96669.22000000
4       285832.48000000
...                 ...
12274   301670.09000000
12275   380386.35000000
12276   176821.44000000
12277   300145.62000000
12278    88506.71000000

[12279 rows x 6 columns], 'df_1h_roseusdt':            Open_Time        Open       Close        High         Low  \
0      1635746400000  0.18050000  0.18251000  0.18251000  0.17987000
1      1635750000000  0.18251000  0.18325000  0.18507000  0.18240000
2      1635753600000  0.18320000  0.18277000  0.18498000  0.18269000
3      1635757200000  0.18277000  0.18313000  0.18400000  0.18250000
4      1635760800000  0.18313000  0.18578000  0.18650000  0.18285000
...              ...         ...         ...         ...         ...
13958  1685998800000  0.05205000  0.05181000  0.05208000  0.05119000
13959  1686002400000  0.05179000  0.05209000  0.05224000  0.05151000
13960  1686006000000  0.05208000  0.05212000  0.05223000  0.05196000
13961  1686009600000  0.05212000  0.05223000  0.05256000  0.05168000
13962  1686013200000  0.05225000  0.05208000  0.05239000  0.05202000

                 Volume
0      1298209.80000000
1      3131338.70000000
2      1455666.70000000
3      2060363.60000000
4      2571658.60000000
...                 ...
13958  6014104.60000000
13959  3602091.70000000
13960  3308809.90000000
13961  5939362.80000000
13962   697209.80000000

[13963 rows x 6 columns], 'df_1h_linausdt':            Open_Time        Open       Close        High         Low  \
0      1635746400000  0.05050000  0.05082000  0.05129000  0.05006000
1      1635750000000  0.05086000  0.05220000  0.05254000  0.05086000
2      1635753600000  0.05218000  0.05191000  0.05269000  0.05171000
3      1635757200000  0.05195000  0.05319000  0.05391000  0.05180000
4      1635760800000  0.05317000  0.05206000  0.05329000  0.05142000
...              ...         ...         ...         ...         ...
13958  1685998800000  0.01436400  0.01439700  0.01446600  0.01417100
13959  1686002400000  0.01439000  0.01445000  0.01453000  0.01432100
13960  1686006000000  0.01444600  0.01447700  0.01467700  0.01442500
13961  1686009600000  0.01448500  0.01441400  0.01457400  0.01429500
13962  1686013200000  0.01441400  0.01430300  0.01441400  0.01425800

                  Volume
0       7372147.72000000
1      13751771.09000000
2      10534965.93000000
3      25149411.66000000
4      22133891.08000000
...                  ...
13958  51939663.19000000
13959  68385681.23000000
13960  70885376.93000000
13961  57458912.96000000
13962  11521660.17000000

[13963 rows x 6 columns], 'df_1h_epxusdt':           Open_Time        Open       Close        High         Low  \
0     1653278400000  0.00196900  0.00169200  0.00318000  0.00155800
1     1653282000000  0.00169900  0.00176100  0.00185000  0.00169400
2     1653285600000  0.00176100  0.00169400  0.00180000  0.00161000
3     1653289200000  0.00169100  0.00166400  0.00175000  0.00161100
4     1653292800000  0.00166700  0.00178500  0.00183200  0.00162900
...             ...         ...         ...         ...         ...
9088  1685998800000  0.00022970  0.00022990  0.00023000  0.00022800
9089  1686002400000  0.00022990  0.00023160  0.00023160  0.00022810
9090  1686006000000  0.00023170  0.00023090  0.00023210  0.00023090
9091  1686009600000  0.00023070  0.00023030  0.00023150  0.00022960
9092  1686013200000  0.00023000  0.00022930  0.00023000  0.00022920

                   Volume
0     3332249659.00000000
1      632237635.00000000
2      420512077.00000000
3      311298824.00000000
4      465932693.00000000
...                   ...
9088   240820896.00000000
9089   168242539.00000000
9090   202137269.00000000
9091   144577773.00000000
9092     8019525.00000000

[9093 rows x 6 columns], 'df_1h_shibusdt':            Open_Time        Open       Close        High         Low  \
0      1635746400000  0.00007001  0.00007042  0.00007100  0.00006823
1      1635750000000  0.00007043  0.00007162  0.00007178  0.00007041
2      1635753600000  0.00007166  0.00007332  0.00007399  0.00007025
3      1635757200000  0.00007335  0.00007249  0.00007370  0.00007208
4      1635760800000  0.00007248  0.00007156  0.00007285  0.00007068
...              ...         ...         ...         ...         ...
13958  1685998800000  0.00000795  0.00000795  0.00000796  0.00000788
13959  1686002400000  0.00000794  0.00000797  0.00000799  0.00000794
13960  1686006000000  0.00000798  0.00000797  0.00000804  0.00000797
13961  1686009600000  0.00000797  0.00000800  0.00000804  0.00000796
13962  1686013200000  0.00000800  0.00000799  0.00000801  0.00000797

                 Volume
0      1012995662018.00
1       940153242221.00
2      1488112717466.00
3      1233113568776.00
4      1152701462038.00
...                 ...
13958    78683278240.00
13959    68279677318.00
13960    62898062988.00
13961    48457998766.00
13962    12407260496.00

[13963 rows x 6 columns], 'df_4h_ethusdt':           Open_Time           Open          Close           High  \
0     1635753600000  4302.94000000  4315.00000000  4354.33000000
1     1635768000000  4315.00000000  4349.98000000  4386.58000000
2     1635782400000  4349.97000000  4364.28000000  4366.00000000
3     1635796800000  4364.28000000  4319.43000000  4365.78000000
4     1635811200000  4319.43000000  4318.83000000  4349.89000000
...             ...            ...            ...            ...
3486  1685952000000  1873.40000000  1869.51000000  1873.81000000
3487  1685966400000  1869.50000000  1820.60000000  1871.20000000
3488  1685980800000  1820.69000000  1806.49000000  1823.90000000
3489  1685995200000  1806.50000000  1810.50000000  1815.88000000
3490  1686009600000  1810.49000000  1808.25000000  1812.00000000

                Low           Volume
0     4294.52000000   74210.59030000
1     4308.25000000   74035.47200000
2     4264.63000000   60730.02210000
3     4278.07000000   43891.13250000
4     4284.43000000   42735.69390000
...             ...              ...
3486  1862.94000000   31604.84180000
3487  1820.29000000  122972.32760000
3488  1778.00000000  244006.88120000
3489  1793.01000000   54834.95860000
3490  1807.00000000   11348.30880000

[3491 rows x 6 columns], 'df_4h_crvusdt':           Open_Time        Open       Close        High         Low  \
0     1635753600000  4.39500000  4.45200000  4.53200000  4.34700000
1     1635768000000  4.45300000  4.48400000  4.51900000  4.31700000
2     1635782400000  4.48500000  4.40200000  4.49500000  4.28800000
3     1635796800000  4.40000000  4.50800000  4.53900000  4.28900000
4     1635811200000  4.50900000  4.40200000  4.63600000  4.32500000
...             ...         ...         ...         ...         ...
3486  1685952000000  0.84200000  0.83800000  0.84400000  0.83300000
3487  1685966400000  0.83800000  0.80400000  0.84000000  0.80300000
3488  1685980800000  0.80400000  0.77300000  0.80400000  0.76800000
3489  1685995200000  0.77400000  0.77400000  0.78000000  0.77200000
3490  1686009600000  0.77400000  0.77100000  0.77800000  0.77100000

                Volume
0     2441231.40000000
1     3585230.50000000
2     1901628.40000000
3     2219941.50000000
4     3881920.40000000
...                ...
3486  1078703.90000000
3487  3261651.40000000
3488  5378149.00000000
3489  1622944.90000000
3490   368220.20000000

[3491 rows x 6 columns], 'df_4h_xecusdt':           Open_Time        Open       Close        High         Low  \
0     1635753600000  0.00017999  0.00018008  0.00018116  0.00017870
1     1635768000000  0.00017986  0.00017956  0.00018082  0.00017800
2     1635782400000  0.00017957  0.00017965  0.00017990  0.00017709
3     1635796800000  0.00017964  0.00017806  0.00017975  0.00017736
4     1635811200000  0.00017806  0.00017732  0.00017870  0.00017700
...             ...         ...         ...         ...         ...
3486  1685952000000  0.00002439  0.00002447  0.00002449  0.00002431
3487  1685966400000  0.00002447  0.00002320  0.00002449  0.00002320
3488  1685980800000  0.00002324  0.00002272  0.00002331  0.00002226
3489  1685995200000  0.00002272  0.00002283  0.00002295  0.00002267
3490  1686009600000  0.00002282  0.00002282  0.00002293  0.00002278

              Volume
0     17664267237.00
1     16297112409.00
2     16171979938.00
3     13212505133.00
4      9308347002.00
...              ...
3486   4613559828.00
3487   9527431802.00
3488  12932617684.00
3489   4437442459.00
3490    851528161.00

[3491 rows x 6 columns], 'df_4h_injusdt':           Open_Time         Open        Close         High          Low  \
0     1635753600000  10.87600000  10.94700000  11.35000000  10.86400000
1     1635768000000  10.95100000  10.87700000  11.03400000  10.79900000
2     1635782400000  10.88100000  10.60300000  10.89600000  10.49600000
3     1635796800000  10.58800000  10.60700000  10.63000000  10.51500000
4     1635811200000  10.60700000  10.56100000  10.62400000  10.49900000
...             ...          ...          ...          ...          ...
3486  1685952000000   7.59000000   7.53000000   7.59600000   7.48400000
3487  1685966400000   7.53100000   7.00400000   7.59500000   7.00000000
3488  1685980800000   7.00100000   7.19900000   7.28900000   6.75300000
3489  1685995200000   7.20300000   7.08200000   7.28200000   7.08000000
3490  1686009600000   7.08100000   7.00300000   7.10100000   6.99200000

                Volume
0      107255.40000000
1       56376.30000000
2      126173.20000000
3       54565.60000000
4       50489.50000000
...                ...
3486   298473.30000000
3487   901056.40000000
3488  1686961.20000000
3489   396597.00000000
3490    96974.20000000

[3491 rows x 6 columns], 'df_4h_imxusdt':           Open_Time        Open       Close        High         Low  \
0     1641801600000  3.75100000  3.73200000  4.30000000  3.71300000
1     1641816000000  3.72900000  3.59700000  3.79900000  3.41900000
2     1641830400000  3.60100000  3.65900000  3.74000000  3.54800000
3     1641844800000  3.65600000  3.78400000  3.89200000  3.64000000
4     1641859200000  3.79100000  3.59100000  3.91000000  3.52500000
...             ...         ...         ...         ...         ...
3066  1685952000000  0.81700000  0.80400000  0.82200000  0.80000000
3067  1685966400000  0.80400000  0.74100000  0.81500000  0.73800000
3068  1685980800000  0.74100000  0.73200000  0.75100000  0.71000000
3069  1685995200000  0.73200000  0.73100000  0.73500000  0.71300000
3070  1686009600000  0.73100000  0.71800000  0.73400000  0.71600000

                Volume
0     1244180.70000000
1      621287.58000000
2      315012.23000000
3      375442.29000000
4      530030.47000000
...                ...
3066   830622.05000000
3067  2222011.68000000
3068  3993792.35000000
3069  1050150.95000000
3070   388652.33000000

[3071 rows x 6 columns], 'df_4h_roseusdt':           Open_Time        Open       Close        High         Low  \
0     1635753600000  0.18320000  0.18519000  0.18719000  0.18250000
1     1635768000000  0.18496000  0.18613000  0.18725000  0.18379000
2     1635782400000  0.18613000  0.18514000  0.18675000  0.18271000
3     1635796800000  0.18496000  0.18429000  0.18600000  0.18267000
4     1635811200000  0.18429000  0.18590000  0.18630000  0.18292000
...             ...         ...         ...         ...         ...
3486  1685952000000  0.05531000  0.05642000  0.05652000  0.05524000
3487  1685966400000  0.05642000  0.05125000  0.05645000  0.05100000
3488  1685980800000  0.05124000  0.05168000  0.05228000  0.04940000
3489  1685995200000  0.05167000  0.05212000  0.05224000  0.05119000
3490  1686009600000  0.05212000  0.05213000  0.05256000  0.05168000

                 Volume
0      8630660.70000000
1      9982127.40000000
2     10758219.30000000
3     10783187.40000000
4      4513259.30000000
...                 ...
3486  22387910.80000000
3487  56575463.90000000
3488  81948514.00000000
3489  20864215.90000000
3490   6647268.00000000

[3491 rows x 6 columns], 'df_4h_linausdt':           Open_Time        Open       Close        High         Low  \
0     1635753600000  0.05218000  0.05138000  0.05391000  0.05102000
1     1635768000000  0.05141000  0.05297000  0.05374000  0.05141000
2     1635782400000  0.05298000  0.05263000  0.05310000  0.05119000
3     1635796800000  0.05261000  0.05282000  0.05315000  0.05184000
4     1635811200000  0.05281000  0.05380000  0.05397000  0.05204000
...             ...         ...         ...         ...         ...
3486  1685952000000  0.01516300  0.01564000  0.01575100  0.01499700
3487  1685966400000  0.01564100  0.01455100  0.01645000  0.01451100
3488  1685980800000  0.01461500  0.01416600  0.01479700  0.01366200
3489  1685995200000  0.01416700  0.01447700  0.01467700  0.01416200
3490  1686009600000  0.01448500  0.01430800  0.01457400  0.01425800

                   Volume
0       74404339.27000000
1       64446213.81000000
2       45430058.44000000
3       21503646.50000000
4       39634616.60000000
...                   ...
3486   665391183.34000000
3487   968385199.45000000
3488  1128796805.98000000
3489   278407637.67000000
3490    69118200.15000000

[3491 rows x 6 columns], 'df_4h_epxusdt':           Open_Time        Open       Close        High         Low  \
0     1653278400000  0.00196900  0.00166400  0.00318000  0.00155800
1     1653292800000  0.00166700  0.00173000  0.00183200  0.00162900
2     1653307200000  0.00173200  0.00165700  0.00175200  0.00158000
3     1653321600000  0.00165700  0.00172600  0.00183000  0.00160000
4     1653336000000  0.00172400  0.00165500  0.00179000  0.00162300
...             ...         ...         ...         ...         ...
2269  1685952000000  0.00025250  0.00025260  0.00025640  0.00024900
2270  1685966400000  0.00025260  0.00023840  0.00025930  0.00023840
2271  1685980800000  0.00023860  0.00022940  0.00024220  0.00022720
2272  1685995200000  0.00022940  0.00023090  0.00023210  0.00022800
2273  1686009600000  0.00023070  0.00022930  0.00023150  0.00022920

                   Volume
0     4696298195.00000000
1     1319677281.00000000
2      975535358.00000000
3     1550835901.00000000
4      828705130.00000000
...                   ...
2269  2341667116.00000000
2270  4180738862.00000000
2271  3831994062.00000000
2272   770712917.00000000
2273   152597298.00000000


In [9]:
def get_klines(symbol, interval):
    global dataframes
    df = dataframes[f'df_{interval}_{symbol}']
    df = df[['Open_Time', 'Open', 'Close', "High", "Low", 'Volume']].astype(float)
    df = df.set_index('Open_Time')

    df.index = pd.to_datetime(df.index, unit='ms') + pd.Timedelta(hours=timezone)
    df = df[~df.index.duplicated(keep='first')]

    return df

In [10]:
symbol_dfs = {}
def multi_timeframes(symbol):
    df = get_klines(symbol, interval_arr[0]).copy() # eth 1h
    df = df.astype(float).round(4)

    for interval in interval_arr:
        raw_df = get_klines(symbol, interval)
        # ema
        for ema in ema_arr:
            column_name = f'ema_{ema}_{interval}' # eth 1h 4th ema
            df[column_name] = ta.trend.EMAIndicator(raw_df.Close, window=ema, fillna=True).ema_indicator()

        # rsi
    #     rsi = ta.momentum.RSIIndicator(raw_df.Close, window = rsi_int)
    #     df[f'rsi_{interval}'] = rsi.rsi()

        # atr
    #         df['atr'] = ta.volatility.average_true_range(df.High, df.Low, df.Close)


    # reset index and set current index as a column
    df = df.reset_index()

    # set new index with integers
    df = df.set_index(pd.RangeIndex(len(df)))

    # time_format(timezone)
    df['Open_Time'] = df['Open_Time'].dt.strftime('%Y-%m-%d %H:%M:%S')

    # fill up higher time frame empty values with equal interval between each value
    df = df.replace('', np.nan)
    df['ema_8_4h'] = df['ema_8_4h'].interpolate()
    df['ema_18_4h'] = df['ema_18_4h'].interpolate()
    df['ema_38_4h'] = df['ema_38_4h'].interpolate()
    symbol_dfs[f'df_{symbol}'] = df
    return symbol_dfs[f'df_{symbol}']

In [11]:
multi_timeframes(symbol_arr[1])
print(symbol_dfs)

{'df_crvusdt':                  Open_Time   Open  Close   High    Low    Volume  ema_8_1h  \
0      2021-11-01 14:00:00  4.301  4.326  4.353  4.270  303124.4  4.326000
1      2021-11-01 15:00:00  4.327  4.394  4.417  4.327  601910.4  4.341111
2      2021-11-01 16:00:00  4.395  4.376  4.436  4.347  380985.9  4.348864
3      2021-11-01 17:00:00  4.376  4.366  4.405  4.362  422365.0  4.352672
4      2021-11-01 18:00:00  4.365  4.404  4.461  4.365  651086.5  4.364078
...                    ...    ...    ...    ...    ...       ...       ...
13958  2023-06-06 05:00:00  0.778  0.777  0.780  0.772  588191.8  0.788948
13959  2023-06-06 06:00:00  0.778  0.778  0.779  0.776  177454.7  0.786515
13960  2023-06-06 07:00:00  0.779  0.774  0.780  0.773  502343.9  0.783734
13961  2023-06-06 08:00:00  0.774  0.774  0.778  0.773  296074.4  0.781571
13962  2023-06-06 09:00:00  0.774  0.771  0.775  0.771   67671.2  0.779222

       ema_18_1h  ema_38_1h  ema_8_4h  ema_18_4h  ema_38_4h
0       4.326000   4.326000       NaN        NaN        NaN
1       4.333158   4.329487       NaN        NaN        NaN
2       4.337668   4.331872  4.452000   4.452000   4.452000
3       4.340650   4.333623  4.453778   4.452842   4.452410
4       4.347318   4.337232  4.455556   4.453684   4.452821
...          ...        ...       ...        ...        ...
13958   0.808393   0.825528  0.809476   0.826569   0.833772
13959   0.805194   0.823091  0.807213   0.825067   0.832956
13960   0.801910   0.820573  0.804950   0.823565   0.832141
13961   0.798972   0.818185  0.802687   0.822063   0.831326
13962   0.796028   0.815765  0.802687   0.822063   0.831326

[13963 rows x 12 columns]}

In [12]:
# def check_cross(df, kd_dir):
#     up = df['slow_k'] > df['slow_d']
#     down = df['slow_k'] < df['slow_d']
#     if kd_dir == 'Up':
#         return up.diff() & up
#     if kd_dir == 'Any':
#         return up.diff()
#     if kd_dir == 'Down':
#         return down.diff() & down


def indicators(df):

# ema
#     for i in (200, 500, 1000):
#         df['ema_'+str(i)] = ta.trend.ema_indicator(df.Close, window=i)

# atr
#     df['atr'] = ta.volatility.average_true_range(df.High, df.Low, df.Close)
    
# rsi
#     rsi_int = 14
#     df['rsi'] = ta.momentum.RSIIndicator(df['Close'], window = rsi_int).rsi()

# bband
    bb_int = 30
    bb_dev = 2
    bb = ta.volatility.BollingerBands(df['Close'], window=bb_int, window_dev=bb_dev)
    df['bb_u'] = bb.bollinger_hband()
    df['bb_m'] = bb.bollinger_mavg()
    df['bb_l'] = bb.bollinger_lband()

# kd
#     df['slow_k']= ta.momentum.stoch(df['High'], df['Low'], df['Close'], 17, 5)
#     df['slow_d'] = ta.momentum.stoch_signal(df['High'], df['Low'], df['Close'], 17, 5)
    
# kd cross
#     df['kd_cross'] = check_cross(df, kd_dir)

In [13]:
def conditions(df, ep_per):
    df['c1'] = df['ema_8_1h'] >= df['ema_18_1h']
    df['c2'] = df['ema_18_1h'] >= df['ema_38_1h']
    df['c3'] = df['ema_8_4h'] >= df['ema_38_4h']
    
    # signal
    df['signal'] = df['c1'] & df['c2'] & df['c3']
    
    # open_entry
    df['open_entry'] = df['signal'] & (df['Low'] <= df['ema_18_4h'] * ep_per)
    
    return df

In [14]:
def entries(df, ep_per, sl_per, sl_det):

    in_position = False
    stop_loss = np.nan
    take_profit = np.nan
    close_val = df['Close']
    open_val = df['Open']
    low_val = df['Low']
    ema_18_val = df['ema_18_4h']
    vol_val = df['Volume']

    df['position'] = ''  # Create an empty column for position
    df['take_profit'] = np.nan

    for index, row in df.iterrows():

        if index == 0:
            continue

        elif row['open_entry']:
            df.at[index, 'entry_p'] = ema_18_val.at[index] * ep_per
            df.at[index, 'stop_loss'] = low_val.at[index] * sl_per
            df.at[index, 'take_profit'] = ema_18_val.at[index] * ep_per * 1.1
            df.at[index, 'position'] = 'Buy'
            in_position = True
            stop_loss = df.at[index, 'stop_loss']
            take_profit = df.at[index, 'take_profit']

        elif in_position and row[sl_det] <= stop_loss:
            df.at[index, 'position'] = 'Stop'
            in_position = False
            stop_loss = np.nan
            take_profit = np.nan

        # set take profit
        elif in_position and row['High'] >= row['bb_u']:
            df.at[index, 'position'] = 'Sell'
            in_position = False
            stop_loss = np.nan
            take_profit = np.nan

        elif in_position and (((vol_val.at[index] > vol_val.shift(1).at[index]) &
                              (open_val.shift(1).at[index] < close_val.shift(1).at[index]) &
                              (open_val.at[index] > close_val.at[index]) & 
                              (low_val.at[index] < open_val.shift(1).at[index])) or
                              (low_val.at[index] <= stop_loss)):
            df.at[index, 'position'] = 'Sell'
            in_position = False
            stop_loss = np.nan
            take_profit = np.nan  
            
    df = df[(df['open_entry']) | (df['position'] != '')]

In [15]:
# 部位回測
def backtest(df, symbol, sl_det):

    df = df.reset_index(drop = True)
    df = df[(df['position'] == 'Buy') |
                  (df['position'] == 'Sell') |
                  (df['position'] == 'Stop')]

    # 一次進場多少單位
    pos_size = 200

    col = ['Open_Time', 'Open', 'Close', 'High', 'Low', 'position','entry_p', 'stop_loss', 'take_profit']
    pos = df[col]
    pos = pos.reset_index(drop = True)


    for index, row in pos.iterrows():

        current_pos = 0

        # 進場
        if pos.at[index, 'position'] == 'Buy':
            pos.at[index, 'size'] = pos_size / pos.at[index, 'entry_p']
            pos.exit_p = np.nan

        # 出場
        if pos.at[index, 'position'] == 'Sell' or pos.at[index, 'position'] == 'Stop':

            # 停利：達成條件時收盤價
            if pos.at[index, 'position'] == 'Sell':
                pos.at[index, 'exit_p'] = pos.at[index, 'Close']
                
#                 for i in range(index -1, -1, -1):
#                     if pos.at[i, 'position'] == 'Buy':
#                         pos.at[index, 'exit_p'] = pos.at[i, 'take_profit']
#                     break

            # 停損：打到進場停損點（往回跌代，直到最近的'Buy'及其'stop_loss'）
            if (pos.at[index, 'position'] == 'Stop') & (sl_det == 'Close'):
                pos.at[index, 'exit_p'] = pos.at[index, 'Close']
                
            if (pos.at[index, 'position'] == 'Stop') & (sl_det == 'Low'):
                for i in range(index -1, -1, -1):
                    if pos.at[i, 'position'] == 'Buy':
                        pos.at[index, 'exit_p'] = pos.at[i, 'stop_loss']
                    break

            # 計算每次出場部位大小（每次出場皆清倉）
            for i in range(index -1, -1, -1):
                if pos.at[i, 'position'] == 'Buy':
                    current_pos += pos.at[i, 'size']
                    if i == 0:
                        pos.at[index, 'size'] = -current_pos
                    else:
                        continue
                else:
                    pos.at[index, 'size'] = -current_pos
                    current_pos = 0
                    break


    # 計算部位價值
    for index, row in pos.iterrows():
        if pos.at[index, 'position'] == 'Buy':
            pos.at[index, 'amt'] = round(pos.at[index, 'size'] * pos.at[index, 'entry_p'], 4)
        elif pos.at[index, 'position'] == 'Sell' or pos.at[index, 'position'] == 'Stop':
            pos.at[index, 'amt'] = round(pos.at[index, 'size'] * pos.at[index, 'exit_p'], 4)


    # 若最後一筆為 Buy，移除該單，迭代驗證
    for index, row in pos.iloc[::-1].iterrows():
        if row['position'] == 'Buy':
            pos = pos.drop(index)
        else:
            break


    # 手續費、滑點、價差
    fee = 0.05 / 100
    amt_abs_sum = pos.amt.abs().sum()
    ttl_fee = amt_abs_sum * fee

    # 損益
    leverage = 10
    ttl_profit = -pos.amt.sum() - ttl_fee

    
    # 計算獲利/虧損次數
    agg_amts = []

    for i in range(len(pos) - 1, -1, -1):

        if pos.loc[i, 'position'] in ['Stop', 'Sell']:

            # look out for the + sign
            total_amt = pos.loc[i, 'amt'] + np.absolute(pos.loc[i, 'amt']) * fee

            # iterate backwards from the current row until reaching another 'Stop' or 'Sell'
            # watch out for the + in total_amt += trading_fee
            j = i - 1
            while j >= 0 and pos.loc[j, 'position'] not in ['Stop', 'Sell']:
                total_amt += pos.loc[j, 'amt']
                trading_fee = np.absolute(pos.loc[j, 'amt']) * fee
                total_amt += trading_fee
                j -= 1

            # add the aggregated amount to the list
            agg_amts.append(total_amt)

    agg_amts.reverse()

    
    # 計算進場最大部位，最大損益
    consec_entry = 0
    position_amt_sum = 0
    max_consec_entry = 0
    max_position = 0
    max_profit = 0
    max_loss = 0

    for index, row in pos.iterrows():

        if row['position'] == 'Buy':

            consec_entry += 1
            position_amt_sum += row['amt']

        elif row['position'] in ['Sell', 'Stop']:

            if consec_entry > max_consec_entry:
                max_consec_entry = consec_entry
                max_position = position_amt_sum

            position_amt_sum += row['amt']

            if -position_amt_sum > max_profit:
                max_profit = -position_amt_sum

            if -position_amt_sum < max_loss:
                max_loss = -position_amt_sum

            consec_entry = 0
            position_amt_sum = 0

        else:
            pass


    # 最大部位
    profit_per = "{:.2f}%".format(ttl_profit / (max_position/leverage) * 100)


    # 勝率
    wins = 0
    loses = 0

    for trade in agg_amts:
        if trade < 0:
            wins += 1
        elif trade > 0:
            loses += 1

    win_rate = "{:.2f}%".format(wins / (wins + loses) * 100)

    cumulative_values = []
    cumulative_sum = 0

    for value in agg_amts:
        cumulative_sum -= value
        cumulative_values.append(cumulative_sum)

    max_drawdown = min(cumulative_values)
    
    # 結果
    result = {'Profit': [round(ttl_profit, 2)],
              'Fee': [round(ttl_fee, 2)],
              'Max_Profit': [round(max_profit, 2)],
              'Max_Loss': [round(max_loss, 2)],
              'Max_Entry': [max_consec_entry],
              'Max_Position': [round(max_position, 2)],
              'Profit_%': [profit_per],
              'Win_Rate': [win_rate],
              'PF_Ratio': [round(ttl_profit/ttl_fee, 2)],
              'Max_Drawdown': [round(max_drawdown,2)]}


    result_df = pd.DataFrame(result)
    
#     pos.to_csv(f'{symbol}_{sl_det}.csv')

    return result_df, ttl_profit, win_rate, ttl_fee

In [16]:
# iterate using start_time, under same time interval, test different variables
def run_backtest():
    
    results_df = pd.DataFrame()
    
    symbol_list = []
    sl_per_list = []
    ep_per_list = []
    sl_det_list = []

    i = 0

    loop_start_time = time.time()
    
    parameters = [(symbol, sl_per, ep_per, sl_det) 
                  for symbol in symbol_arr
                  for sl_per in sl_per_arr
                  for ep_per in ep_per_arr
                  for sl_det in sl_det_arr]
    
    for symbol, sl_per, ep_per, sl_det in parameters:

        df = multi_timeframes(symbol)
        df = df.reset_index()
        indicators(df)
        conditions(df, ep_per)
        entries(df, ep_per, sl_per, sl_det)
        backtest_df, ttl_profit, win_rate, fee = backtest(df, symbol, sl_det)

        results_df = pd.concat([results_df, backtest_df], ignore_index = True)

        symbol_list.append(symbol)
        sl_per_list.append(sl_per)
        ep_per_list.append(ep_per)
        sl_det_list.append(sl_det)

        i += 1
        
        print(f" {i} - {symbol}, sl: {sl_per}, tp: {ep_per}, {sl_det}, {round(ttl_profit, 2)}, {round(fee, 2)}, {round(ttl_profit/fee, 2)}, {win_rate} ")

    loop_end_time = time.time()

    print("Time taken to execute for loop:", loop_end_time - loop_start_time, "seconds")

    results_df['symbol'] = symbol_list
    results_df['sl_per'] = sl_per_list
    results_df['ep_per'] = ep_per_list
    results_df['sl_det'] = sl_det_list

    results_df = results_df[['symbol',
                             'sl_per', 'ep_per', 'sl_det',
                             'Profit', 'Fee', 'Max_Profit', 'Max_Loss',
                             'Max_Entry', 'Max_Position', 'Profit_%', 'Win_Rate', 'PF_Ratio', 'Max_Drawdown'
                            ]]
    
    return results_df

In [17]:
results_df = run_backtest()
results_df = results_df.sort_values('Profit', ascending = False)
# print(results_df)

 1 - ethusdt, sl: 0.998, tp: 0.999, Close, 231.99, 28.73, 8.07, 61.84%
 2 - ethusdt, sl: 0.998, tp: 0.999, Low, 243.71, 28.74, 8.48, 55.26%
 3 - ethusdt, sl: 0.998, tp: 1.001, Close, 345.1, 59.2, 5.83, 63.16%
 4 - ethusdt, sl: 0.998, tp: 1.001, Low, 380.77, 59.22, 6.43, 60.53%
 5 - ethusdt, sl: 0.998, tp: 1.003, Close, 315.0, 92.6, 3.4, 58.82%
 6 - ethusdt, sl: 0.998, tp: 1.003, Low, 361.29, 92.63, 3.9, 56.86%
 7 - ethusdt, sl: 0.998, tp: 1.01, Close, -21.98, 269.52, -0.08, 52.07%
 8 - ethusdt, sl: 0.998, tp: 1.01, Low, 233.07, 269.65, 0.86, 50.00%
 9 - ethusdt, sl: 0.995, tp: 0.999, Close, 213.75, 28.72, 7.44, 61.84%
 10 - ethusdt, sl: 0.995, tp: 0.999, Low, 224.62, 28.73, 7.82, 56.58%
 11 - ethusdt, sl: 0.995, tp: 1.001, Close, 331.02, 59.2, 5.59, 64.91%
 12 - ethusdt, sl: 0.995, tp: 1.001, Low, 341.53, 59.2, 5.77, 62.28%
 13 - ethusdt, sl: 0.995, tp: 1.003, Close, 306.1, 92.6, 3.31, 59.87%
 14 - ethusdt, sl: 0.995, tp: 1.003, Low, 319.25, 92.61, 3.45, 58.55%
 15 - ethusdt, sl: 0.995, tp: 1.01, Close, -67.75, 269.5, -0.25, 52.74%
 16 - ethusdt, sl: 0.995, tp: 1.01, Low, 29.15, 269.55, 0.11, 52.32%
 17 - ethusdt, sl: 0.99, tp: 0.999, Close, 189.15, 28.71, 6.59, 60.53%
 18 - ethusdt, sl: 0.99, tp: 0.999, Low, 200.35, 28.71, 6.98, 57.89%
 19 - ethusdt, sl: 0.99, tp: 1.001, Close, 271.4, 59.17, 4.59, 64.60%
 20 - ethusdt, sl: 0.99, tp: 1.001, Low, 303.13, 59.18, 5.12, 63.72%
 21 - ethusdt, sl: 0.99, tp: 1.003, Close, 233.9, 92.56, 2.53, 60.67%
 22 - ethusdt, sl: 0.99, tp: 1.003, Low, 255.68, 92.57, 2.76, 60.00%
 23 - ethusdt, sl: 0.99, tp: 1.01, Close, -214.32, 269.43, -0.8, 53.65%
 24 - ethusdt, sl: 0.99, tp: 1.01, Low, -170.22, 269.45, -0.63, 53.65%
 25 - crvusdt, sl: 0.998, tp: 0.999, Close, 607.75, 28.72, 21.16, 69.33%
 26 - crvusdt, sl: 0.998, tp: 0.999, Low, 603.97, 28.72, 21.03, 69.33%
 27 - crvusdt, sl: 0.998, tp: 1.001, Close, 692.32, 41.97, 16.5, 67.33%
 28 - crvusdt, sl: 0.998, tp: 1.001, Low, 690.15, 41.97, 16.45, 66.34%
 29 - crvusdt, sl: 0.998, tp: 1.003, Close, 813.66, 57.44, 14.17, 67.46%
 30 - crvusdt, sl: 0.998, tp: 1.003, Low, 820.96, 57.44, 14.29, 65.08%
 31 - crvusdt, sl: 0.998, tp: 1.01, Close, 943.18, 144.14, 6.54, 63.13%
 32 - crvusdt, sl: 0.998, tp: 1.01, Low, 1011.26, 144.18, 7.01, 59.60%
 33 - crvusdt, sl: 0.995, tp: 0.999, Close, 596.82, 28.71, 20.79, 71.23%
 34 - crvusdt, sl: 0.995, tp: 0.999, Low, 588.3, 28.71, 20.49, 71.23%
 35 - crvusdt, sl: 0.995, tp: 1.001, Close, 677.29, 41.96, 16.14, 67.68%
 36 - crvusdt, sl: 0.995, tp: 1.001, Low, 675.68, 41.96, 16.1, 67.68%
 37 - crvusdt, sl: 0.995, tp: 1.003, Close, 797.16, 57.43, 13.88, 67.48%
 38 - crvusdt, sl: 0.995, tp: 1.003, Low, 798.63, 57.43, 13.91, 66.67%
 39 - crvusdt, sl: 0.995, tp: 1.01, Close, 951.09, 144.15, 6.6, 63.54%
 40 - crvusdt, sl: 0.995, tp: 1.01, Low, 927.35, 144.14, 6.43, 62.50%
 41 - crvusdt, sl: 0.99, tp: 0.999, Close, 597.13, 28.71, 20.8, 74.65%
 42 - crvusdt, sl: 0.99, tp: 0.999, Low, 579.46, 28.7, 20.19, 74.65%
 43 - crvusdt, sl: 0.99, tp: 1.001, Close, 682.14, 41.96, 16.26, 70.83%
 44 - crvusdt, sl: 0.99, tp: 1.001, Low, 663.07, 41.95, 15.81, 70.83%
 45 - crvusdt, sl: 0.99, tp: 1.003, Close, 806.87, 57.43, 14.05, 72.03%
 46 - crvusdt, sl: 0.99, tp: 1.003, Low, 786.88, 57.42, 13.7, 71.19%
 47 - crvusdt, sl: 0.99, tp: 1.01, Close, 1064.97, 144.2, 7.39, 66.48%
 48 - crvusdt, sl: 0.99, tp: 1.01, Low, 1054.85, 144.2, 7.32, 65.93%
 49 - xecusdt, sl: 0.998, tp: 0.999, Close, -435649.84, 274.71, -1585.84, 3.05%
 50 - xecusdt, sl: 0.998, tp: 0.999, Low, -435649.84, 274.71, -1585.84, 3.05%
 51 - xecusdt, sl: 0.998, tp: 1.001, Close, -435764.98, 275.26, -1583.13, 3.05%
 52 - xecusdt, sl: 0.998, tp: 1.001, Low, -435764.98, 275.26, -1583.13, 3.05%
 53 - xecusdt, sl: 0.998, tp: 1.003, Close, -435880.84, 276.0, -1579.29, 3.03%
 54 - xecusdt, sl: 0.998, tp: 1.003, Low, -435880.84, 276.0, -1579.29, 3.03%
 55 - xecusdt, sl: 0.998, tp: 1.01, Close, -436303.23, 279.99, -1558.29, 3.03%
 56 - xecusdt, sl: 0.998, tp: 1.01, Low, -436303.23, 279.99, -1558.29, 3.03%
 57 - xecusdt, sl: 0.995, tp: 0.999, Close, -435649.84, 274.71, -1585.84, 3.05%
 58 - xecusdt, sl: 0.995, tp: 0.999, Low, -435649.84, 274.71, -1585.84, 3.05%
 59 - xecusdt, sl: 0.995, tp: 1.001, Close, -435764.98, 275.26, -1583.13, 3.05%
 60 - xecusdt, sl: 0.995, tp: 1.001, Low, -435764.98, 275.26, -1583.13, 3.05%
 61 - xecusdt, sl: 0.995, tp: 1.003, Close, -435880.84, 276.0, -1579.29, 3.03%
 62 - xecusdt, sl: 0.995, tp: 1.003, Low, -435880.84, 276.0, -1579.29, 3.03%
 63 - xecusdt, sl: 0.995, tp: 1.01, Close, -436303.23, 279.99, -1558.29, 3.03%
 64 - xecusdt, sl: 0.995, tp: 1.01, Low, -436303.23, 279.99, -1558.29, 3.03%
 65 - xecusdt, sl: 0.99, tp: 0.999, Close, -435649.84, 274.71, -1585.84, 3.05%
 66 - xecusdt, sl: 0.99, tp: 0.999, Low, -435649.84, 274.71, -1585.84, 3.05%
 67 - xecusdt, sl: 0.99, tp: 1.001, Close, -435764.98, 275.26, -1583.13, 3.05%
 68 - xecusdt, sl: 0.99, tp: 1.001, Low, -435764.98, 275.26, -1583.13, 3.05%
 69 - xecusdt, sl: 0.99, tp: 1.003, Close, -435880.84, 276.0, -1579.29, 3.03%
 70 - xecusdt, sl: 0.99, tp: 1.003, Low, -435880.84, 276.0, -1579.29, 3.03%
 71 - xecusdt, sl: 0.99, tp: 1.01, Close, -436303.23, 279.99, -1558.29, 3.03%
 72 - xecusdt, sl: 0.99, tp: 1.01, Low, -436303.23, 279.99, -1558.29, 3.03%
 73 - injusdt, sl: 0.998, tp: 0.999, Close, 791.89, 33.81, 23.42, 72.53%
 74 - injusdt, sl: 0.998, tp: 0.999, Low, 801.58, 33.82, 23.7, 69.23%
 75 - injusdt, sl: 0.998, tp: 1.001, Close, 903.76, 45.27, 19.96, 71.68%
 76 - injusdt, sl: 0.998, tp: 1.001, Low, 920.53, 45.28, 20.33, 65.49%
 77 - injusdt, sl: 0.998, tp: 1.003, Close, 1040.54, 57.15, 18.21, 67.94%
 78 - injusdt, sl: 0.998, tp: 1.003, Low, 1078.82, 57.17, 18.87, 66.41%
 79 - injusdt, sl: 0.998, tp: 1.01, Close, 1792.6, 141.37, 12.68, 64.22%
 80 - injusdt, sl: 0.998, tp: 1.01, Low, 1923.41, 141.43, 13.6, 63.36%
 81 - injusdt, sl: 0.995, tp: 0.999, Close, 776.3, 33.81, 22.96, 72.53%
 82 - injusdt, sl: 0.995, tp: 0.999, Low, 793.8, 33.81, 23.48, 71.43%
 83 - injusdt, sl: 0.995, tp: 1.001, Close, 887.19, 45.27, 19.6, 71.68%
 84 - injusdt, sl: 0.995, tp: 1.001, Low, 907.03, 45.28, 20.03, 68.14%
 85 - injusdt, sl: 0.995, tp: 1.003, Close, 1022.38, 57.14, 17.89, 68.70%
 86 - injusdt, sl: 0.995, tp: 1.003, Low, 1062.32, 57.16, 18.59, 68.70%
 87 - injusdt, sl: 0.995, tp: 1.01, Close, 1814.9, 141.38, 12.84, 65.37%
 88 - injusdt, sl: 0.995, tp: 1.01, Low, 1898.8, 141.42, 13.43, 65.37%
 89 - injusdt, sl: 0.99, tp: 0.999, Close, 771.21, 33.8, 22.82, 73.33%
 90 - injusdt, sl: 0.99, tp: 0.999, Low, 774.35, 33.8, 22.91, 72.22%
 91 - injusdt, sl: 0.99, tp: 1.001, Close, 905.15, 45.28, 19.99, 72.07%
 92 - injusdt, sl: 0.99, tp: 1.001, Low, 907.74, 45.28, 20.05, 71.17%
 93 - injusdt, sl: 0.99, tp: 1.003, Close, 1035.03, 57.15, 18.11, 70.54%
 94 - injusdt, sl: 0.99, tp: 1.003, Low, 1051.96, 57.15, 18.41, 70.54%
 95 - injusdt, sl: 0.99, tp: 1.01, Close, 1950.14, 141.45, 13.79, 67.84%
 96 - injusdt, sl: 0.99, tp: 1.01, Low, 2012.39, 141.48, 14.22, 67.40%
 97 - imxusdt, sl: 0.998, tp: 0.999, Close, 757.11, 26.99, 28.05, 69.33%
 98 - imxusdt, sl: 0.998, tp: 0.999, Low, 761.25, 26.99, 28.2, 64.00%
 99 - imxusdt, sl: 0.998, tp: 1.001, Close, 813.91, 35.02, 23.24, 71.00%
 100 - imxusdt, sl: 0.998, tp: 1.001, Low, 827.56, 35.03, 23.62, 66.00%
 101 - imxusdt, sl: 0.998, tp: 1.003, Close, 1010.96, 50.13, 20.17, 67.72%
 102 - imxusdt, sl: 0.998, tp: 1.003, Low, 1059.59, 50.15, 21.13, 65.35%
 103 - imxusdt, sl: 0.998, tp: 1.01, Close, 1320.46, 107.51, 12.28, 65.75%
 104 - imxusdt, sl: 0.998, tp: 1.01, Low, 1519.23, 107.61, 14.12, 62.43%
 105 - imxusdt, sl: 0.995, tp: 0.999, Close, 759.65, 26.99, 28.14, 69.33%
 106 - imxusdt, sl: 0.995, tp: 0.999, Low, 750.3, 26.99, 27.8, 65.33%
 107 - imxusdt, sl: 0.995, tp: 1.001, Close, 815.89, 35.03, 23.29, 71.00%
 108 - imxusdt, sl: 0.995, tp: 1.001, Low, 810.27, 35.02, 23.14, 67.00%
 109 - imxusdt, sl: 0.995, tp: 1.003, Close, 1016.18, 50.13, 20.27, 70.08%
 110 - imxusdt, sl: 0.995, tp: 1.003, Low, 1034.39, 50.14, 20.63, 66.93%
 111 - imxusdt, sl: 0.995, tp: 1.01, Close, 1301.28, 107.5, 12.1, 65.92%
 112 - imxusdt, sl: 0.995, tp: 1.01, Low, 1441.77, 107.57, 13.4, 64.25%

 113 - imxusdt, sl: 0.99, tp: 0.999, Close, 799.67, 27.01, 29.6, 72.97%
 114 - imxusdt, sl: 0.99, tp: 0.999, Low, 775.33, 27.0, 28.71, 67.57%
 115 - imxusdt, sl: 0.99, tp: 1.001, Close, 845.17, 35.04, 24.12, 73.74%
 116 - imxusdt, sl: 0.99, tp: 1.001, Low, 823.31, 35.03, 23.5, 68.69%
 117 - imxusdt, sl: 0.99, tp: 1.003, Close, 1046.31, 50.15, 20.86, 72.80%
 118 - imxusdt, sl: 0.99, tp: 1.003, Low, 1027.59, 50.14, 20.49, 68.80%
 119 - imxusdt, sl: 0.99, tp: 1.01, Close, 1304.79, 107.51, 12.14, 66.85%
 120 - imxusdt, sl: 0.99, tp: 1.01, Low, 1362.58, 107.54, 12.67, 66.29%
 121 - roseusdt, sl: 0.998, tp: 0.999, Close, 632.99, 37.14, 17.05, 58.70%
 122 - roseusdt, sl: 0.998, tp: 0.999, Low, 666.32, 37.15, 17.94, 55.43%
 123 - roseusdt, sl: 0.998, tp: 1.001, Close, 686.53, 47.97, 14.31, 60.71%
 124 - roseusdt, sl: 0.998, tp: 1.001, Low, 723.98, 47.99, 15.09, 56.25%
 125 - roseusdt, sl: 0.998, tp: 1.003, Close, 810.31, 64.64, 12.54, 62.07%
 126 - roseusdt, sl: 0.998, tp: 1.003, Low, 860.55, 64.66, 13.31, 59.31%
 127 - roseusdt, sl: 0.998, tp: 1.01, Close, 800.83, 152.28, 5.26, 56.48%
 128 - roseusdt, sl: 0.998, tp: 1.01, Low, 1035.79, 152.39, 6.8, 56.48%
 129 - roseusdt, sl: 0.995, tp: 0.999, Close, 694.82, 37.17, 18.7, 63.33%
 130 - roseusdt, sl: 0.995, tp: 0.999, Low, 703.43, 37.17, 18.92, 60.00%
 131 - roseusdt, sl: 0.995, tp: 1.001, Close, 753.98, 48.0, 15.71, 64.22%
 132 - roseusdt, sl: 0.995, tp: 1.001, Low, 757.12, 48.0, 15.77, 60.55%
 133 - roseusdt, sl: 0.995, tp: 1.003, Close, 876.48, 64.67, 13.55, 64.29%
 134 - roseusdt, sl: 0.995, tp: 1.003, Low, 883.64, 64.67, 13.66, 62.14%
 135 - roseusdt, sl: 0.995, tp: 1.01, Close, 885.08, 152.32, 5.81, 58.57%
 136 - roseusdt, sl: 0.995, tp: 1.01, Low, 979.76, 152.37, 6.43, 57.62%
 137 - roseusdt, sl: 0.99, tp: 0.999, Close, 719.73, 37.18, 19.36, 63.64%
 138 - roseusdt, sl: 0.99, tp: 0.999, Low, 729.44, 37.18, 19.62, 63.64%
 139 - roseusdt, sl: 0.99, tp: 1.001, Close, 768.67, 48.01, 16.01, 65.42%
 140 - roseusdt, sl: 0.99, tp: 1.001, Low, 781.14, 48.01, 16.27, 65.42%
 141 - roseusdt, sl: 0.99, tp: 1.003, Close, 889.14, 64.68, 13.75, 66.42%
 142 - roseusdt, sl: 0.99, tp: 1.003, Low, 908.07, 64.69, 14.04, 66.42%
 143 - roseusdt, sl: 0.99, tp: 1.01, Close, 1055.25, 152.4, 6.92, 60.10%
 144 - roseusdt, sl: 0.99, tp: 1.01, Low, 1103.68, 152.43, 7.24, 60.10%
 145 - linausdt, sl: 0.998, tp: 0.999, Close, 988.49, 33.51, 29.5, 68.82%
 146 - linausdt, sl: 0.998, tp: 0.999, Low, 1035.65, 33.53, 30.88, 66.67%
 147 - linausdt, sl: 0.998, tp: 1.001, Close, 1157.76, 45.2, 25.61, 69.23%
 148 - linausdt, sl: 0.998, tp: 1.001, Low, 1267.85, 45.26, 28.01, 67.31%
 149 - linausdt, sl: 0.998, tp: 1.003, Close, 1404.5, 60.13, 23.36, 68.94%
 150 - linausdt, sl: 0.998, tp: 1.003, Low, 1523.06, 60.19, 25.3, 65.91%
 151 - linausdt, sl: 0.998, tp: 1.01, Close, 2185.64, 126.56, 17.27, 67.68%
 152 - linausdt, sl: 0.998, tp: 1.01, Low, 2373.56, 126.65, 18.74, 66.67%
 153 - linausdt, sl: 0.995, tp: 0.999, Close, 1006.73, 33.52, 30.03, 69.57%
 154 - linausdt, sl: 0.995, tp: 0.999, Low, 1027.47, 33.53, 30.64, 67.39%
 155 - linausdt, sl: 0.995, tp: 1.001, Close, 1192.85, 45.22, 26.38, 69.90%
 156 - linausdt, sl: 0.995, tp: 1.001, Low, 1268.08, 45.26, 28.02, 67.96%
 157 - linausdt, sl: 0.995, tp: 1.003, Close, 1439.86, 60.15, 23.94, 69.47%
 158 - linausdt, sl: 0.995, tp: 1.003, Low, 1511.1, 60.19, 25.11, 66.41%
 159 - linausdt, sl: 0.995, tp: 1.01, Close, 2218.56, 126.57, 17.53, 68.02%
 160 - linausdt, sl: 0.995, tp: 1.01, Low, 2292.51, 126.61, 18.11, 66.50%
 161 - linausdt, sl: 0.99, tp: 0.999, Close, 1009.11, 33.52, 30.1, 70.65%
 162 - linausdt, sl: 0.99, tp: 0.999, Low, 1010.76, 33.52, 30.15, 68.48%
 163 - linausdt, sl: 0.99, tp: 1.001, Close, 1195.22, 45.22, 26.43, 70.87%
 164 - linausdt, sl: 0.99, tp: 1.001, Low, 1235.39, 45.24, 27.31, 68.93%
 165 - linausdt, sl: 0.99, tp: 1.003, Close, 1440.11, 60.15, 23.94, 69.77%
 166 - linausdt, sl: 0.99, tp: 1.003, Low, 1464.47, 60.16, 24.34, 67.44%
 167 - linausdt, sl: 0.99, tp: 1.01, Close, 2245.49, 126.59, 17.74, 68.04%
 168 - linausdt, sl: 0.99, tp: 1.01, Low, 2178.05, 126.55, 17.21, 67.53%
 169 - epxusdt, sl: 0.998, tp: 0.999, Close, -2711.0, 159.92, -16.95, 29.69%
 170 - epxusdt, sl: 0.998, tp: 0.999, Low, -2712.1, 159.92, -16.96, 29.69%
 171 - epxusdt, sl: 0.998, tp: 1.001, Close, -3032.45, 161.76, -18.75, 29.69%
 172 - epxusdt, sl: 0.998, tp: 1.001, Low, -3033.54, 161.76, -18.75, 29.69%
 173 - epxusdt, sl: 0.998, tp: 1.003, Close, -3323.68, 163.82, -20.29, 29.69%
 174 - epxusdt, sl: 0.998, tp: 1.003, Low, -3324.77, 163.82, -20.3, 29.69%
 175 - epxusdt, sl: 0.998, tp: 1.01, Close, -4406.43, 174.28, -25.28, 28.36%
 176 - epxusdt, sl: 0.998, tp: 1.01, Low, -4407.51, 174.28, -25.29, 28.36%
 177 - epxusdt, sl: 0.995, tp: 0.999, Close, -2711.0, 159.92, -16.95, 29.69%
 178 - epxusdt, sl: 0.995, tp: 0.999, Low, -2713.74, 159.92, -16.97, 29.69%
 179 - epxusdt, sl: 0.995, tp: 1.001, Close, -3032.45, 161.76, -18.75, 29.69%
 180 - epxusdt, sl: 0.995, tp: 1.001, Low, -3035.18, 161.76, -18.76, 29.69%
 181 - epxusdt, sl: 0.995, tp: 1.003, Close, -3323.68, 163.82, -20.29, 29.69%
 182 - epxusdt, sl: 0.995, tp: 1.003, Low, -3326.4, 163.82, -20.31, 29.69%
 183 - epxusdt, sl: 0.995, tp: 1.01, Close, -4406.43, 174.28, -25.28, 28.36%
 184 - epxusdt, sl: 0.995, tp: 1.01, Low, -4409.13, 174.28, -25.3, 28.36%
 185 - epxusdt, sl: 0.99, tp: 0.999, Close, -2711.0, 159.92, -16.95, 29.69%
 186 - epxusdt, sl: 0.99, tp: 0.999, Low, -2716.47, 159.92, -16.99, 29.69%
 187 - epxusdt, sl: 0.99, tp: 1.001, Close, -3032.45, 161.76, -18.75, 29.69%
 188 - epxusdt, sl: 0.99, tp: 1.001, Low, -3037.9, 161.76, -18.78, 29.69%
 189 - epxusdt, sl: 0.99, tp: 1.003, Close, -3323.68, 163.82, -20.29, 29.69%
 190 - epxusdt, sl: 0.99, tp: 1.003, Low, -3329.12, 163.82, -20.32, 29.69%
 191 - epxusdt, sl: 0.99, tp: 1.01, Close, -4406.43, 174.28, -25.28, 28.36%
 192 - epxusdt, sl: 0.99, tp: 1.01, Low, -4411.83, 174.28, -25.31, 28.36%
 193 - shibusdt, sl: 0.998, tp: 0.999, Close, -587575.23, 301.36, -1949.73, 0.65%
 194 - shibusdt, sl: 0.998, tp: 0.999, Low, -587575.23, 301.36, -1949.73, 0.65%
 195 - shibusdt, sl: 0.998, tp: 1.001, Close, -587590.66, 301.36, -1949.83, 0.65%
 196 - shibusdt, sl: 0.998, tp: 1.001, Low, -587590.66, 301.36, -1949.83, 0.65%
 197 - shibusdt, sl: 0.998, tp: 1.003, Close, -587606.03, 301.35, -1949.93, 0.65%
 198 - shibusdt, sl: 0.998, tp: 1.003, Low, -587606.03, 301.35, -1949.93, 0.65%
 199 - shibusdt, sl: 0.998, tp: 1.01, Close, -587659.33, 301.32, -1950.28, 0.65%
 200 - shibusdt, sl: 0.998, tp: 1.01, Low, -587659.33, 301.32, -1950.28, 0.65%
 201 - shibusdt, sl: 0.995, tp: 0.999, Close, -587575.23, 301.36, -1949.73, 0.65%
 202 - shibusdt, sl: 0.995, tp: 0.999, Low, -587575.23, 301.36, -1949.73, 0.65%
 203 - shibusdt, sl: 0.995, tp: 1.001, Close, -587590.66, 301.36, -1949.83, 0.65%
 204 - shibusdt, sl: 0.995, tp: 1.001, Low, -587590.66, 301.36, -1949.83, 0.65%
 205 - shibusdt, sl: 0.995, tp: 1.003, Close, -587606.03, 301.35, -1949.93, 0.65%
 206 - shibusdt, sl: 0.995, tp: 1.003, Low, -587606.03, 301.35, -1949.93, 0.65%
 207 - shibusdt, sl: 0.995, tp: 1.01, Close, -587659.33, 301.32, -1950.28, 0.65%
 208 - shibusdt, sl: 0.995, tp: 1.01, Low, -587659.33, 301.32, -1950.28, 0.65%
 209 - shibusdt, sl: 0.99, tp: 0.999, Close, -587575.23, 301.36, -1949.73, 0.65%
 210 - shibusdt, sl: 0.99, tp: 0.999, Low, -587575.23, 301.36, -1949.73, 0.65%
 211 - shibusdt, sl: 0.99, tp: 1.001, Close, -587590.66, 301.36, -1949.83, 0.65%
 212 - shibusdt, sl: 0.99, tp: 1.001, Low, -587590.66, 301.36, -1949.83, 0.65%
 213 - shibusdt, sl: 0.99, tp: 1.003, Close, -587606.03, 301.35, -1949.93, 0.65%
 214 - shibusdt, sl: 0.99, tp: 1.003, Low, -587606.03, 301.35, -1949.93, 0.65%
 215 - shibusdt, sl: 0.99, tp: 1.01, Close, -587659.33, 301.32, -1950.28, 0.65%
 216 - shibusdt, sl: 0.99, tp: 1.01, Low, -587659.33, 301.32, -1950.28, 0.65%
Time taken to execute for loop: 226.8560287952423 seconds

In [18]:
results_df.to_csv(f'results_df_023.csv')